import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const academy=fs.readFileSync(new URL('../src/academy.js',import.meta.url),'utf8');
const pack=fs.readFileSync(new URL('../scripts/package-web.mjs',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../app/sw.js',import.meta.url),'utf8');
const packagedApp=fs.readFileSync(new URL('../app/src/app.js',import.meta.url),'utf8');
const packagedAcademy=fs.readFileSync(new URL('../app/src/academy.js',import.meta.url),'utf8');
for(const token of ['renderAcademyCenter','academyContextTopics','academyContextHelp','refreshAcademyProgress','remapro-academy','academy-manager-visibility','startAcademyTour','academy-copy-context'])assert.ok(app.includes(token),token);
assert.ok(app.includes("scope:'all'"),'cross-app scope');
assert.ok(app.includes('canManageVisibility:cloudOrgAdmin()'),'visibility admin guard');
assert.ok(app.includes('hubAcademyAutoRows'),'automatic onboarding progress');
assert.ok(academy.includes('academy-onboarding'),'first steps onboarding');
assert.ok(academy.includes('Guide mis à jour'),'stale content warning');
assert.ok(pack.includes("'academy-content.js'"));assert.ok(pack.includes("'academy.js'"));
assert.ok(sw.includes("./src/academy-content.js"));assert.ok(sw.includes("./src/academy.js"));
assert.equal(packagedApp,app,'packaged Hub app matches source');
assert.equal(packagedAcademy,academy,'packaged Academy matches source');
console.log('Hub Academy integration and packaged runtime checks passed');
