import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const cloud=fs.readFileSync(new URL('../src/cloud.js',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
for(const token of ['function trainingView','TRAINING_REAL_ACTION_BLOCKED','if(state.trainingMode)return;','academy-help-context','academyFunction','academy-scope','academy-copy-context','posOrgAdmin','canManageVisibility:posOrgAdmin()','trackTrainingProgress','academyChromeText'])assert.ok((app+cloud).includes(token),token);
const a=app.indexOf('function trainingView'),b=app.indexOf('function academyTourView',a),training=app.slice(a,b);
assert.doesNotMatch(training,/posFunction\(|queueCommand\(|printEscPosText\(/,'training sandbox must not call real sale or printer');
for(const text of ['MODE ENTRAÎNEMENT','TRAINING MODE','TRAININGSMODUS','MODALITÀ FORMAZIONE'])assert.ok(training.includes(text),text);
assert.ok(training.includes('cartName'),'localized training cart');
assert.ok(app.includes("trackTrainingProgress(1)"),'training cash step progress');
assert.ok(app.includes("trackTrainingProgress(3)"),'training order step progress');
assert.ok(app.includes("trackTrainingProgress(6)"),'training payment step progress');
assert.ok(app.includes("trackTrainingProgress(7,'completed')"),'training completion progress');
assert.ok(app.includes("metadata:{training:true}"),'training progress metadata');
assert.ok(app.includes("academy:{query:'',scope:'all'"),'cross-app academy scope state');
assert.ok(app.includes("document.getElementById('academy-scope')"),'cross-app scope binding');
assert.ok(app.includes("if(!posOrgAdmin()||!org)return"),'org admin visibility mutation guard');
assert.ok(app.includes("application:'ReMaPro POS'"),'safe support context');
assert.ok(sw.includes('./src/academy-content.js'));assert.ok(sw.includes('./src/academy.js'));
assert.match(sw,/remapro-pos-shell-v\d{4}[-a-z0-9]*-\d{8}/,'offline cache refreshed');
assert.equal(JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8')).version,'0.27.0');
console.log('POS Academy training, permissions, support and offline checks passed');

assert.ok(app.includes("contextHelp:'Aide contextuelle'"));
assert.ok(app.includes("contextHelp:'Contextual help'"));
assert.ok(app.includes("contextHelp:'Kontexthilfe'"));
assert.ok(app.includes("contextHelp:'Aiuto contestuale'"));
assert.ok(app.includes('academyChromeText().contextCopied'));
