import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const source=readFileSync('supabase/functions/remapro-admin/index.ts','utf8');
const app=readFileSync('src/app.js','utf8');

assert.match(source,/withSupabase\(\{auth:"user"\}/);
assert.match(source,/ORG_ADMIN_ROLES/);
assert.match(source,/RESTAURANT_ADMIN_ROLES/);
assert.match(source,/MEMBER_PERMISSIONS/);
for(const permission of ['finance','hr','documents','recipes','ai'])assert.match(source,new RegExp(`"${permission}"`));
for(const action of ['list-members','list-audit','invite-member','update-member','set-member-active','revoke-member'])assert.match(source,new RegExp(`"${action}"`));
assert.match(source,/allowedScope=\(ids:string\[\]\)=>orgAdmin\|\|ids\.every/);
assert.match(source,/targetUserId===callerUserId/,'managers must not edit their own role');
assert.match(source,/ORG_ADMIN_ROLES\.has\(String\(m\.role\)\)/,'owner/admin memberships must be protected');
assert.match(source,/ctx\.supabaseAdmin\.auth\.admin\.inviteUserByEmail/);
assert.match(source,/audit_logs/);
assert.match(source,/member\.updated/);
assert.match(source,/member\.deactivated/);
assert.match(source,/restaurantCount\|\|0\)>=commercial\.restaurantLimit/,'server must enforce purchased establishment slots');
assert.match(source,/14\*86400000/,'fallback trial duration must be fourteen days');
assert.match(source,/organizationUserCapacity/,'organization access must centralize the ten-user account limit');
assert.match(source,/users\.size<10\|\|!!target&&users\.has\(target\)/,'existing active users may be reassigned without consuming another slot');
assert.match(source,/if\(active&&!\(await organizationUserCapacity\(ctx,organizationId,targetUserId\)\)\.allowed\)/,'reactivating a user must enforce the ten-user cap');
assert.ok((source.match(/organizationUserCapacity\(ctx,organizationId,targetUserId\)/g)||[]).length>=2,'member reactivation and member update must both enforce capacity');
assert.match(source,/restaurant_limit/,'subscription access must load purchased establishment slots');
assert.match(app,/cloudAccountPanel/);
assert.match(app,/memberAccessForm/);
assert.match(app,/data-cloud-member-toggle/);
assert.match(app,/refreshCloudAdminData/);
console.log('V27.10 manager delegation and account audit guards OK');
