import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const workflow=readFileSync('.github/workflows/android.yml','utf8');
const activity=readFileSync('android-native/MainActivity.java','utf8');
const launcher=readFileSync('android-native/ic_launcher.xml','utf8');
const roundLauncher=readFileSync('android-native/ic_launcher_round.xml','utf8');
const launcherColors=readFileSync('android-native/remaprohub_colors.xml','utf8');
const launcherForeground=readFileSync('android-native/remaprohub_foreground.xml','utf8');
const legacyLauncher=readFileSync('android-native/ic_launcher_legacy.xml','utf8');
const cameraPatch=readFileSync('scripts/patch-android-camera.mjs','utf8');
const manifest=JSON.parse(readFileSync('app/manifest.json','utf8'));
assert.equal(manifest.display,'standalone');
assert.ok(workflow.indexOf('npx cap add android')<workflow.indexOf('install -m 644 android-native/MainActivity.java'));
assert.ok(workflow.indexOf('install -m 644 android-native/MainActivity.java')<workflow.indexOf('npx cap sync android'));
assert.ok(workflow.indexOf('npx cap sync android')<workflow.indexOf('Apply ReMaPro Android branding'));
assert.ok(workflow.indexOf('npx cap sync android')<workflow.indexOf('Enable camera capture'));
assert.ok(workflow.indexOf('Enable camera capture')<workflow.indexOf('Apply ReMaPro Android branding'));
assert.match(workflow,/android\.permission\.CAMERA/);
assert.match(cameraPatch,/android\.permission\.CAMERA/);
assert.match(cameraPatch,/<manifest\\b\[\^>\]\*>/);
assert.ok(workflow.indexOf('Apply ReMaPro Android branding')<workflow.indexOf('./gradlew assembleDebug'));
assert.doesNotMatch(workflow,/assets-remaprohub-logo\.png/);
assert.match(workflow,/ic_launcher_legacy\.xml android\/app\/src\/main\/res\/mipmap-anydpi\/ic_launcher\.xml/);
assert.match(launcher,/@drawable\/remaprohub_foreground/);
assert.match(launcher,/@color\/remaprohub_icon_bg/);
assert.match(roundLauncher,/@drawable\/remaprohub_foreground/);
assert.match(launcherColors,/#8D7B6A/i);
assert.doesNotMatch(launcherForeground,/<inset\b/);
assert.match(launcherForeground,/M430,225/);
assert.match(legacyLauncher,/#8D7B6A/i);
assert.match(activity,/WindowCompat\.setDecorFitsSystemWindows\(getWindow\(\), false\)/);
assert.match(activity,/controller\.hide\(WindowInsetsCompat\.Type\.systemBars\(\)\)/);
assert.match(activity,/BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE/);
assert.match(activity,/onWindowFocusChanged\(boolean hasFocus\)/);
console.log('Android fullscreen packaging checks OK');
