import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const workflow=readFileSync('.github/workflows/android.yml','utf8');
const activity=readFileSync('android-native/MainActivity.java','utf8');
const launcher=readFileSync('android-native/ic_launcher.xml','utf8');
const roundLauncher=readFileSync('android-native/ic_launcher_round.xml','utf8');
const launcherColors=readFileSync('android-native/remaprohub_colors.xml','utf8');
const manifest=JSON.parse(readFileSync('app/manifest.json','utf8'));
assert.equal(manifest.display,'fullscreen');
assert.ok(workflow.indexOf('npx cap add android')<workflow.indexOf('install -m 644 android-native/MainActivity.java'));
assert.ok(workflow.indexOf('install -m 644 android-native/MainActivity.java')<workflow.indexOf('npx cap sync android'));
assert.ok(workflow.indexOf('npx cap sync android')<workflow.indexOf('Apply ReMaPro Android branding'));
assert.ok(workflow.indexOf('Apply ReMaPro Android branding')<workflow.indexOf('./gradlew assembleDebug'));
assert.match(workflow,/app\/assets-remaprohub-logo\.png android\/app\/src\/main\/res\/drawable-nodpi\/remaprohub_logo\.png/);
assert.match(launcher,/@drawable\/remaprohub_logo/);
assert.match(launcher,/@color\/remaprohub_icon_bg/);
assert.match(roundLauncher,/@drawable\/remaprohub_logo/);
assert.match(launcherColors,/#F5EFE6/i);
assert.match(activity,/WindowCompat\.setDecorFitsSystemWindows\(getWindow\(\), false\)/);
assert.match(activity,/controller\.hide\(WindowInsetsCompat\.Type\.systemBars\(\)\)/);
assert.match(activity,/BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE/);
assert.match(activity,/onWindowFocusChanged\(boolean hasFocus\)/);
console.log('Android fullscreen packaging checks OK');
