import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{catalogue,LANGS}from'../src/i18n.js';import{recordFinance,financeTotals,updateRecord,removeRecord,saveDocument,recordOrder,updateOrder,removeOrder,recordPurchase,updatePurchase,removePurchase}from'../src/store.js';
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8'),store=readFileSync(new URL('../src/store.js',import.meta.url),'utf8');
const modules=['dashboard','operations','orders','products','haccp','finance','documents','stock','suppliers','purchases','invoices','team','planning','leave','training','briefing','recipes','reservations','customers','loyalty','incidents','waste','maintenance','equipment','handover','deliveries','allergens','recalls','cleaning','audits','checklists','alerts','goals','help','more','settings'];for(const name of modules)assert.match(app,new RegExp(`\\b${name}\\b`),`missing module ${name}`);
assert.doesNotMatch(app,/applyFullLanguage|MutationObserver|translateRenderedHTML|canonicalTranslation|location\.replace/);assert.match(app,/updateRecord/);assert.match(app,/removeRecord/);assert.match(app,/saveDocument/);assert.match(app,/id="customerForm"/);assert.match(app,/state\.customers\.unshift/);assert.match(store,/localStorage\.setItem/);assert.match(store,/financeHistory:/);assert.match(store,/export function recordFinance/);assert.match(store,/export function financeTotals/);
// Security + persistent CRUD guards: persisted free text must be escaped and edit/delete must save before rerender.
assert.match(app,/const state=load\(\),persist=\(\)=>save\(state\),esc=/,'missing HTML escaping boundary');assert.match(app,/replace\(\/\[&<>[\\\\]?"'\]\//,'escaping must cover HTML metacharacters');assert.match(app,/data-remove=/,'missing delete controls');assert.match(app,/data-edit=/,'missing edit controls');assert.match(app,/data-edit-form=/,'missing inline edit forms');assert.match(app,/data-cancel-edit/,'missing edit cancellation');assert.match(app,/removeRecord\(state,b\.dataset\.remove,\+b\.dataset\.index\)/,'delete must retain shared CRUD fallback');assert.match(app,/updateOrder\(state,index/);assert.match(app,/removeOrder\(state/);assert.match(app,/recordPurchase\(state/);for(const collection of ['customers','suppliers','team','temps','stock','shifts','recipes','reservations','incidents','waste','products','loyalty','briefings','invoices','checklists','alerts','training','leave','equipment','audits','cleaning','deliveries','allergens','recalls']){assert.match(app,new RegExp(`actions\\('${collection}',i\\)`),`missing edit/delete actions for ${collection}`);assert.match(app,new RegExp(`data-edit-form="${collection}"`),`missing edit form for ${collection}`);assert.match(app,new RegExp(`collection==='${collection}'`),`missing persistent edit handler for ${collection}`)}
const literal=[...app.matchAll(/\bt\('([^']+)'\)/g)].map(x=>x[1]),dynamic=['dashboard','operations','haccp','finance','documents','stock','suppliers','team','planning','recipes','reservations','customers','incidents','waste','more','settings','day','week','month','traceability','nonConformity','recipeSheet','purchaseOrder','inspectionPrep','inventory','openKitchen','temperatureCheck','diningSetup','cashCheck','closingCleaning','edit','delete','cancel'],keys=new Set([...literal,...dynamic]);for(const lang of LANGS){const cat=catalogue(lang);for(const key of keys){assert.ok(Object.prototype.hasOwnProperty.call(cat,key),`${lang}: missing translation key ${key}`);assert.notEqual(cat[key],key,`${lang}: untranslated raw key ${key}`)}}
for(const field of ['products','loyalty','briefings','invoices','checklists','alerts','documentEntries','sales','financeHistory','stock','temps','suppliers','purchases','team','shifts','incidents','waste','reservations','customers','recipes','maintenance','handover','products','loyalty','briefings','invoices','checklists','alerts','goals','training','leave','equipment','audits','cleaning','deliveries','allergens','recalls'])assert.match(store,new RegExp(`\\b${field}:`),`missing state field ${field}`);
const financeState={financeHistory:[],revenue:0,covers:0,expenses:0};recordFinance(financeState,{date:'2026-09-17',revenue:100,covers:10,expenses:20});recordFinance(financeState,{date:'2026-09-16',revenue:50,covers:5,expenses:10});recordFinance(financeState,{date:'2026-09-17',revenue:120,covers:12,expenses:25});assert.equal(financeState.financeHistory.length,2,'same-day finance entry must be replaced');const week=financeTotals(financeState,'week',new Date('2026-09-17T23:00:00'));assert.deepEqual({revenue:week.revenue,covers:week.covers,expenses:week.expenses},{revenue:170,covers:17,expenses:35});
console.log(`V27 architecture: ${keys.size} UI translation keys validated across ${LANGS.length} languages; secure CRUD and finance aggregation validated`);
const crud={stock:[{name:'A',qty:1,price:2}],documentEntries:[]};assert.equal(updateRecord(crud,'stock',0,{qty:3}),true);assert.equal(crud.stock[0].qty,3);assert.equal(removeRecord(crud,'stock',0),true);assert.equal(crud.stock.length,0);global.localStorage={setItem(){},getItem(){return null},removeItem(){}};assert.equal(saveDocument(crud,{type:'traceability',date:'2026-09-17',title:'Lot 1',details:'OK'}),true);assert.equal(crud.documentEntries.length,1);

// Transactional finance reconciliation guards.
const tx={orders:[],purchases:[],financeHistory:[],revenue:0,covers:0,expenses:0};recordOrder(tx,{reference:'T1',amount:100,status:'paid',date:'2026-09-18'});assert.equal(tx.financeHistory[0].revenue,100);updateOrder(tx,0,{amount:125,status:'paid',date:'2026-09-18'});assert.equal(tx.financeHistory[0].revenue,125);updateOrder(tx,0,{amount:125,status:'open',date:'2026-09-18'});assert.equal(tx.financeHistory[0].revenue,0);updateOrder(tx,0,{amount:80,status:'paid',date:'2026-09-18'});removeOrder(tx,0);assert.equal(tx.financeHistory[0].revenue,0);recordPurchase(tx,{supplier:'S',date:'2026-09-18',amount:40,note:''});assert.equal(tx.financeHistory[0].expenses,40);updatePurchase(tx,0,{supplier:'S',date:'2026-09-18',amount:55,note:''});assert.equal(tx.financeHistory[0].expenses,55);removePurchase(tx,0);assert.equal(tx.financeHistory[0].expenses,0);

// Low-stock threshold must survive creation/edit wiring and drive dashboard signal.
assert.match(app,/stockForm'[\s\S]{0,180}min:\+f\.get\('min'\)/,'stock creation must persist minimum threshold');assert.match(app,/collection==='stock'[\s\S]{0,160}min:\+d\.get\('min'\)/,'stock edits must persist minimum threshold');assert.match(app,/filter\(x=>\+x\.qty<=\+\(x\.min\|\|0\)/,'dashboard must derive low-stock alerts from thresholds');

// Manual finance entry must not erase transactional order/purchase amounts.
const mixed={orders:[],purchases:[],financeHistory:[],revenue:0,covers:0,expenses:0};recordOrder(mixed,{reference:'M1',amount:75,status:'paid',date:'2026-09-18'});recordPurchase(mixed,{supplier:'S',amount:20,date:'2026-09-18',note:''});recordFinance(mixed,{date:'2026-09-18',revenue:100,covers:8,expenses:30});assert.equal(mixed.financeHistory[0].revenue,175);assert.equal(mixed.financeHistory[0].expenses,50);recordFinance(mixed,{date:'2026-09-18',revenue:120,covers:9,expenses:35});assert.equal(mixed.financeHistory[0].revenue,195);assert.equal(mixed.financeHistory[0].expenses,55);

// Every restored operational screen must be reachable from the dashboard module launcher.
for(const m of ['purchases','invoices','leave','training','maintenance','equipment','deliveries','allergens','recalls','cleaning','audits','checklists','alerts','goals','briefing','handover','help'])assert.match(app,new RegExp(`const modules=\\[[^;]*['\"]${m}['\"]`),`dashboard must expose ${m}`);

// Existing V27 finance rows must be migrated into source-separated fields without changing totals.
global.localStorage={setItem(){},getItem(){return JSON.stringify({financeHistory:[{date:'2026-09-10',revenue:90,covers:6,expenses:25}]})},removeItem(){}};const migrated=(await import('../src/store.js?migration-guard')).load();assert.equal(migrated.financeHistory[0].manualRevenue,90);assert.equal(migrated.financeHistory[0].manualExpenses,25);assert.equal(migrated.financeHistory[0].orderRevenue,0);assert.equal(migrated.financeHistory[0].purchaseExpenses,0);assert.equal(migrated.financeHistory[0].revenue,90);assert.equal(migrated.financeHistory[0].expenses,25);

// Every rendered data-entry form must have a submit binding; settings has its dedicated listener.
const renderedForms=[...app.matchAll(/id="([A-Za-z]+Form)"/g)].map(x=>x[1]);const helperBindings=new Set([...app.matchAll(/form\('([^']+)'/g)].map(x=>x[1]));for(const id of renderedForms){if(id==='settingsForm')assert.match(app,/getElementById\('settingsForm'\)\?\.addEventListener\('submit'/);else assert.ok(helperBindings.has(id),`missing submit binding for ${id}`)}

// Navigation targets must resolve to a screen and stock edits must retain alert thresholds.
const screenFns=new Set([...app.matchAll(/function ([A-Za-z]+)\(\)\{/g)].map(x=>x[1]));for(const m of ['dashboard','operations','finance','documents','more',...['orders','products','haccp','stock','suppliers','purchases','invoices','team','planning','leave','training','recipes','reservations','customers','loyalty','incidents','waste','maintenance','equipment','deliveries','allergens','recalls','cleaning','audits','checklists','alerts','goals','briefing','handover','help']])assert.ok(screenFns.has(m),`missing screen function ${m}`);assert.match(app,/collection==='stock'[^;]+min:\+d\.get\('min'\)/,'stock edit must preserve minimum threshold');
