import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{catalogue,LANGS}from'../src/i18n.js';import{recordFinance,financeTotals}from'../src/store.js';
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8'),store=readFileSync(new URL('../src/store.js',import.meta.url),'utf8');
const modules=['dashboard','operations','haccp','finance','documents','stock','suppliers','team','planning','recipes','reservations','customers','incidents','waste','more','settings'];for(const name of modules)assert.match(app,new RegExp(`\\b${name}\\b`),`missing module ${name}`);
assert.doesNotMatch(app,/applyFullLanguage|MutationObserver|translateRenderedHTML|canonicalTranslation|location\.replace/);assert.match(app,/import\{load,save,recordFinance,financeTotals\}from'\.\/store\.js'/);assert.match(app,/id="customerForm"/);assert.match(app,/state\.customers\.unshift/);assert.match(store,/localStorage\.setItem/);assert.match(store,/financeHistory:/);assert.match(store,/export function recordFinance/);assert.match(store,/export function financeTotals/);
// Security + persistent CRUD guards: persisted free text must be escaped and edit/delete must save before rerender.
assert.match(app,/const state=load\(\),persist=\(\)=>save\(state\),esc=/,'missing HTML escaping boundary');assert.match(app,/replace\(\/\[&<>\\"'\]\//,'escaping must cover HTML metacharacters');assert.match(app,/data-remove=/,'missing delete controls');assert.match(app,/data-edit=/,'missing edit controls');assert.match(app,/data-edit-form=/,'missing inline edit forms');assert.match(app,/data-cancel-edit/,'missing edit cancellation');assert.match(app,/a\.splice\(i,1\);editing=null;persist\(\);render\(\)/,'delete must persist and rerender');for(const collection of ['customers','suppliers','team']){assert.match(app,new RegExp(`actions\\('${collection}',i\\)`),`missing edit/delete actions for ${collection}`);assert.match(app,new RegExp(`data-edit-form="${collection}"`),`missing edit form for ${collection}`);assert.match(app,new RegExp(`collection==='${collection}'`),`missing persistent edit handler for ${collection}`)}
const literal=[...app.matchAll(/\bt\('([^']+)'\)/g)].map(x=>x[1]),dynamic=['dashboard','operations','haccp','finance','documents','stock','suppliers','team','planning','recipes','reservations','customers','incidents','waste','more','settings','day','week','month','traceability','nonConformity','recipeSheet','purchaseOrder','inspectionPrep','inventory','openKitchen','temperatureCheck','diningSetup','cashCheck','closingCleaning','edit','delete','cancel'],keys=new Set([...literal,...dynamic]);for(const lang of LANGS){const cat=catalogue(lang);for(const key of keys){assert.ok(Object.prototype.hasOwnProperty.call(cat,key),`${lang}: missing translation key ${key}`);assert.notEqual(cat[key],key,`${lang}: untranslated raw key ${key}`)}}
for(const field of ['sales','financeHistory','stock','temps','suppliers','purchases','team','shifts','incidents','waste','reservations','customers','recipes','maintenance','handover'])assert.match(store,new RegExp(`\\b${field}:`),`missing state field ${field}`);
const financeState={financeHistory:[],revenue:0,covers:0,expenses:0};recordFinance(financeState,{date:'2026-09-17',revenue:100,covers:10,expenses:20});recordFinance(financeState,{date:'2026-09-16',revenue:50,covers:5,expenses:10});recordFinance(financeState,{date:'2026-09-17',revenue:120,covers:12,expenses:25});assert.equal(financeState.financeHistory.length,2,'same-day finance entry must be replaced');const week=financeTotals(financeState,'week',new Date('2026-09-17T23:00:00'));assert.deepEqual({revenue:week.revenue,covers:week.covers,expenses:week.expenses},{revenue:170,covers:17,expenses:35});
console.log(`V27 architecture: ${keys.size} UI translation keys validated across ${LANGS.length} languages; secure CRUD and finance aggregation validated`);