import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
for(const file of ['order.html','order.css','order.js'])assert.ok(readFileSync(new URL('../app/'+file,import.meta.url)).length>100,file+' missing');
const html=readFileSync(new URL('../app/order.html',import.meta.url),'utf8');
const js=readFileSync(new URL('../app/order.js',import.meta.url),'utf8');
const sw=readFileSync(new URL('../app/sw.js',import.meta.url),'utf8');
const pub=readFileSync(new URL('../supabase/functions/remapro-direct-order/index.ts',import.meta.url),'utf8');
const admin=readFileSync(new URL('../supabase/functions/remapro-direct-order-admin/index.ts',import.meta.url),'utf8');
assert.ok(html.includes('Content-Security-Policy'),'public order CSP required');
assert.ok(js.includes("x-remapro-order-token"),'QR token must be sent separately from request body');
assert.ok(js.includes("location.hash"),'QR secret must be read from fragment');
assert.ok(js.includes("crypto.randomUUID()"),'client idempotency key required');
assert.ok(js.includes('paymentMethod'),'QR UI must carry payment preference');
assert.ok(js.includes('requestedFor'),'Click & Collect pickup time must be carried');
assert.ok(js.includes("toISOString()"),'pickup time must be normalized with the customer device timezone');
assert.ok(js.includes('payment_status'),'QR confirmation must show POS-confirmed payment state');
assert.ok(js.includes("kioskMode=qs.get('kiosk')==='1'"),'kiosk query mode missing');
assert.ok(js.includes("clientMode:kioskMode?'kiosk':'web'"),'kiosk orders must be tagged');
assert.ok(js.includes('scheduleKioskReset'),'kiosk automatic reset missing');
assert.ok(pub.includes('kioskClient?300:20'),'kiosk needs a dedicated safe rate limit');
assert.ok(pub.includes('Kiosk mode unavailable'),'server must reject kiosk mode on non-kiosk channels');
assert.ok(!js.includes('payment_status:"paid"'),'client must never mark payment as paid');
assert.ok(pub.includes('paymentMethod==="counter"?"unpaid":"pending"'),'public server may request payment but never self-confirm it');
assert.ok(pub.includes('Payment method unavailable'),'payment preference must be server allowlisted');
assert.ok(pub.includes('Invalid pickup time'),'pickup scheduling must be validated server-side');
assert.ok(pub.includes('payment_method'),'public status must expose payment state from the POS');
assert.ok(pub.includes('token_hash'),'server token hash validation required');
assert.ok(pub.includes('Too many recent orders'),'rate limit required');
assert.ok(pub.includes('pos_catalog_items'),'server-side catalog pricing required');
assert.ok(pub.includes('unit_price:unit'),'server-calculated price snapshot required');
assert.ok(admin.includes('QRCode'),'admin QR SVG generation required');
assert.ok(sw.includes('./order.html')&&sw.includes('./order.js'),'ordering shell must be cache-listed');
console.log('Secure public QR ordering checks passed');
