import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const app=readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const admin=readFileSync(new URL('../supabase/functions/remapro-direct-order-admin/index.ts',import.meta.url),'utf8');
const sync=readFileSync(new URL('../supabase/functions/remapro-pos-sync/index.ts',import.meta.url),'utf8');
assert.ok(app.includes("remapro-direct-order-admin"),'Hub must call direct-order admin function');
for(const token of ['directOrderAdminCard','createDirectOrderChannel','rotateDirectOrderChannel','directOrderPrint'])assert.ok(app.includes(token),token+' missing');
assert.ok(admin.includes('token_hash'),'plain QR secret must not be persisted');
assert.ok(admin.includes('QRCode.toString'),'QR SVG generation required');
for(const action of ['list_direct_orders','claim_direct_order','link_direct_order','reject_direct_order'])assert.ok(sync.includes(action),action+' POS bridge missing');
console.log('Hub QR administration and POS bridge checks passed');
