import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {saveDocument,updateDocument} from '../src/store.js';
const app=readFileSync('src/app.js','utf8');
globalThis.localStorage={setItem(){}};
const state={documentEntries:[]};
assert.equal(saveDocument(state,{type:'inventory',date:'2026-09-18',title:'Initial',details:'A\nB'}),true);
const createdAt=state.documentEntries[0].createdAt;
assert.equal(updateDocument(state,0,{type:'inventory',date:'2026-09-19',title:'Révisé',details:'A\nC'}),true);
assert.equal(state.documentEntries.length,1);
assert.equal(state.documentEntries[0].createdAt,createdAt);
assert.equal(state.documentEntries[0].details,'A\nC');
assert.equal(updateDocument(state,2,{title:'Invalide'}),false);
assert.match(app,/data-doc-preview/);
assert.match(app,/document-preview/);
assert.match(app,/data-doc-edit/);
assert.match(app,/updateDocument\(state,editing.index,record\)/);
console.log('Document preview and edit lifecycle OK');
const structured={documentEntries:[]};
saveDocument(structured,{type:'traceability',date:'2026-09-18',title:'Lot',details:'',fields:{product:'Tomatoes',lot:'A12',bad_key:'discard'}});
assert.deepEqual(structured.documentEntries[0].fields,{product:'Tomatoes',lot:'A12'});
updateDocument(structured,0,{type:'traceability',date:'2026-09-18',title:'Lot',details:'Note',fields:{product:'Carrots',lot:'B13'}});
assert.equal(structured.documentEntries[0].fields.product,'Carrots');
const legalState={documentEntries:[]};
saveDocument(legalState,{type:'payslip',date:'2026-09-19',title:'Paie septembre',details:'',fields:{employeeName:'Alice',grossSalary:'5000'},legal:{country:'CH',name:'Suisse',reviewedAt:'2026-09-19',source:'SECO / Fedlex',note:'Variable'}});
assert.equal(legalState.documentEntries[0].legal.country,'CH');
assert.equal(legalState.documentEntries[0].legal.reviewedAt,'2026-09-19');
assert.match(app,/DOCUMENT_FIELDS=\{traceability:/);
assert.match(app,/documentFieldsForm\(selected,entry\?\.fields,/);
assert.match(app,/documentFieldsView\(preview\)/);
assert.match(app,/legalPack\(/);
assert.match(app,/legalCountry/);
assert.match(app,/document-section/);
console.log('Structured and country-aware document fields OK');
