import assert from 'node:assert/strict';
import {load,recordOrder,updateOrder,recordPurchase,updatePurchase,recordFinance,financeTotals,financeDayTotals,localDate} from '../src/store.js';
globalThis.localStorage={getItem:()=>null,setItem(){}};
const state=load(),date='2026-09-18',now=new Date('2026-09-18T12:00:00');
recordOrder(state,{reference:'Table 1',amount:100,status:'paid',date});
recordPurchase(state,{supplier:'Supplier',amount:20,date});
recordFinance(state,{date,revenue:50,covers:3,expenses:5});
assert.deepEqual([financeTotals(state,'day',now).revenue,financeTotals(state,'day',now).expenses],[150,25]);
recordFinance(state,{date,revenue:50,covers:3,expenses:5});
assert.deepEqual([financeTotals(state,'day',now).revenue,financeTotals(state,'day',now).expenses],[150,25]);
assert.equal(state.financeHistory[0].manualRevenue,50);
assert.equal(state.financeHistory[0].manualExpenses,5);
assert.equal(financeTotals(state,'day',new Date('2026-09-19T12:00:00')).revenue,0);
assert.equal(financeTotals(state,'month',new Date('2026-10-02T12:00:00')).revenue,0);
assert.equal(financeTotals(state,'month',now).revenue,150);
const selectedDay=load();
recordFinance(selectedDay,{date:'2026-09-17',revenue:40,covers:2,expenses:3});
recordFinance(selectedDay,{date:'2026-09-18',revenue:70,covers:4,expenses:5});
assert.deepEqual([financeDayTotals(selectedDay,'2026-09-17').revenue,financeDayTotals(selectedDay,'2026-09-17').expenses,financeDayTotals(selectedDay,'2026-09-17').covers],[40,3,2]);
assert.deepEqual([financeDayTotals(selectedDay,'2026-09-18').revenue,financeDayTotals(selectedDay,'2026-09-18').expenses,financeDayTotals(selectedDay,'2026-09-18').covers],[70,5,4]);
state.financeHistory.push({date:'2026-09-13',revenue:500,covers:2,expenses:10});
assert.equal(financeTotals(state,'week',now).revenue,150);
assert.equal(financeTotals(state,'week',new Date('2026-09-14T12:00:00')).revenue,0);
state.financeHistory.pop();
process.env.TZ='Europe/Zurich';assert.equal(localDate(new Date('2026-09-18T22:30:00Z')),'2026-09-19');
const OriginalDate=globalThis.Date;
globalThis.Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:['2026-09-18T22:30:00Z']))}};
try{
  const undated=load();
  assert.equal(recordOrder(undated,{reference:'Night',amount:1,status:'paid'}).date,'2026-09-19');
  assert.equal(recordPurchase(undated,{supplier:'Night',amount:1}).date,'2026-09-19');
}finally{globalThis.Date=OriginalDate}

const invalidFinance=load();
assert.equal(recordOrder(invalidFinance,{reference:'Bad',amount:-1,status:'paid',date}),false);
assert.equal(recordPurchase(invalidFinance,{supplier:'Bad',amount:-1,date}),false);
recordOrder(invalidFinance,{reference:'Good',amount:10,status:'paid',date});
assert.equal(updateOrder(invalidFinance,0,{amount:-5}),false);
recordPurchase(invalidFinance,{supplier:'Good',amount:10,date});
assert.equal(updatePurchase(invalidFinance,0,{amount:-5}),false);
console.log('Finance entries and date boundaries OK');
import {readFileSync} from 'node:fs';const restoredUi=readFileSync('src/restored.js','utf8');assert.match(restoredUi,/exportDailyManagementPdf/);assert.match(restoredUi,/dailyManagerReportData\(s\)/);assert.match(restoredUi,/lastManagementReportDate/);
// Removing a manual entry must preserve paid orders and purchases on that date.
import {removeRecord} from '../src/store.js';
assert.equal(removeRecord(state,'financeHistory',0),true);
assert.equal(state.financeHistory.length,1);
assert.equal(state.financeHistory[0].revenue,100);
assert.equal(state.financeHistory[0].expenses,20);
assert.equal(state.financeHistory[0].covers,0);
assert.equal(removeRecord(state,'financeHistory',10),false);
import {removeOrder,removePurchase} from '../src/store.js';
assert.equal(removeOrder(state,0),true);
assert.equal(state.financeHistory[0].expenses,20);
assert.equal(removePurchase(state,0),true);
assert.equal(state.financeHistory[0].revenue,0);
assert.equal(state.financeHistory[0].expenses,0);

const financeUi=readFileSync('src/app.js','utf8');
for(const token of ['loadPosDailySummary','financeStateWithPos','posFinanceRefreshTimer','mergePosFinance','loadPosFinanceData(today(),{force:true})']) assert.ok(financeUi.includes(token),token+' missing');
assert.match(restoredUi,/posRevenue=n\(day\.posRevenue\)/);
assert.match(restoredUi,/money\(orderTotal\+posRevenue\)/);
const posEdge=readFileSync('supabase/functions/remapro-pos-sync/index.ts','utf8');
assert.match(posEdge,/operatorExempt[\s\S]*"daily_summary"/);
assert.match(posEdge,/if\(action==="daily_summary"\)\{\s*if\(!manager\)return json\(\{error:"Manager access required"\},403\)/);
