import assert from 'node:assert/strict';
import {load,recordOrder,recordPurchase,recordFinance,financeTotals,localDate} from '../src/store.js';
globalThis.localStorage={getItem:()=>null,setItem(){}};
const state=load(),date='2026-09-18',now=new Date('2026-09-18T12:00:00');
recordOrder(state,{reference:'Table 1',amount:100,status:'paid',date});
recordPurchase(state,{supplier:'Supplier',amount:20,date});
recordFinance(state,{date,revenue:50,covers:3,expenses:5});
assert.deepEqual([financeTotals(state,'day',now).revenue,financeTotals(state,'day',now).expenses],[150,25]);
recordFinance(state,{date,revenue:50,covers:3,expenses:5});
assert.deepEqual([financeTotals(state,'day',now).revenue,financeTotals(state,'day',now).expenses],[150,25]);
assert.equal(state.financeHistory[0].manualRevenue,50);
assert.equal(state.financeHistory[0].manualExpenses,5);
assert.equal(financeTotals(state,'day',new Date('2026-09-19T12:00:00')).revenue,0);
assert.equal(financeTotals(state,'month',new Date('2026-10-02T12:00:00')).revenue,0);
assert.equal(financeTotals(state,'month',now).revenue,150);
state.financeHistory.push({date:'2026-09-13',revenue:500,covers:2,expenses:10});
assert.equal(financeTotals(state,'week',now).revenue,150);
assert.equal(financeTotals(state,'week',new Date('2026-09-14T12:00:00')).revenue,0);
state.financeHistory.pop();
process.env.TZ='Europe/Zurich';assert.equal(localDate(new Date('2026-09-18T22:30:00Z')),'2026-09-19');
console.log('Finance entries and date boundaries OK');
// Removing a manual entry must preserve paid orders and purchases on that date.
import {removeRecord} from '../src/store.js';
assert.equal(removeRecord(state,'financeHistory',0),true);
assert.equal(state.financeHistory.length,1);
assert.equal(state.financeHistory[0].revenue,100);
assert.equal(state.financeHistory[0].expenses,20);
assert.equal(state.financeHistory[0].covers,0);
assert.equal(removeRecord(state,'financeHistory',10),false);
import {removeOrder,removePurchase} from '../src/store.js';
assert.equal(removeOrder(state,0),true);
assert.equal(state.financeHistory[0].expenses,20);
assert.equal(removePurchase(state,0),true);
assert.equal(state.financeHistory[0].revenue,0);
assert.equal(state.financeHistory[0].expenses,0);
