import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleText=fs.readFileSync(new URL('../src/floor-plan.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const pos=fs.readFileSync(new URL('../src/pos.js',import.meta.url),'utf8');
const edge=fs.readFileSync(new URL('../supabase/functions/remapro-pos-sync/index.ts',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migrations/20260923205000_pos_floor_plans.sql',import.meta.url),'utf8');
const tableLinksMigration=fs.readFileSync(new URL('../supabase/migrations/20260923211500_pos_order_table_links.sql',import.meta.url),'utf8');
assert.ok(moduleText.includes('renderFloorPlanEditor'));
assert.ok(moduleText.includes('bindFloorPlanEditor'));
assert.ok(moduleText.includes("type:'table'"));
assert.ok(moduleText.includes('data-floor-element'));
assert.ok(app.includes('floor-plan-editor-root'));
assert.ok(app.includes('publishCurrentFloorPlan'));
assert.ok(app.includes('seedFloorPlanFromTables(posAdminState.tables||[])'));
assert.ok(app.includes('onActivate:()=>activateCurrentFloorPlan()'));
assert.ok(moduleText.includes('floorPlanActivate'));
assert.ok(pos.includes('loadPosFloorPlanAdmin'));
assert.ok(edge.includes('action==="floor_plan_current"'));
assert.ok(edge.includes('action==="publish_floor_plan"'));
assert.ok(edge.includes('synchronizeTablesFromFloorPlan'));
assert.ok(edge.includes('FLOOR_PLAN_TABLE_IN_USE'));
assert.ok(edge.includes('restaurant_workspaces'));
assert.ok(edge.includes('durationMinutes'));
assert.ok(migration.includes('create table if not exists public.pos_floor_plans'));
assert.ok(migration.includes('create table if not exists public.pos_floor_plan_versions'));
assert.ok(tableLinksMigration.includes('create table if not exists public.pos_order_table_links'));
assert.ok(edge.includes('action==="merge_order_table"'));
assert.ok(edge.includes('action==="unmerge_order_table"'));
assert.ok(edge.includes('linked_table_ids'));
console.log('ReMaPro visual floor-plan checks passed');
