import assert from 'node:assert/strict';
import {recordHaccpTemperature,verifyHaccpChain,haccpReadingStatus,cancelHaccpReading,resolveHaccpReading,updateRecord,removeRecord} from '../src/store.js';
const state={temps:[],haccpAudit:[]};
const first=recordHaccpTemperature(state,{zone:'Cold room',equipment:'Fridge 1',value:3,min:0,max:5,responsible:'Alice',photo:'data:image/jpeg;base64,AA'});
assert.ok(first?.integrity);
assert.equal(first.conforming,true);
assert.equal(recordHaccpTemperature(state,{zone:'Cold room',equipment:'Fridge 1',value:9,min:0,max:5,responsible:'Alice',action:''}),false);
const second=recordHaccpTemperature(state,{zone:'Cold room',equipment:'Fridge 1',value:9,min:0,max:5,responsible:'Alice',action:'Move products and inspect unit'});
assert.equal(second.conforming,false);
assert.equal(second.prevIntegrity,first.integrity);
assert.equal(verifyHaccpChain(state),true);
assert.ok(resolveHaccpReading(state,0,{reason:'Unit repaired and temperature restored',responsible:'Bob'}));
assert.equal(haccpReadingStatus(state,second.id).resolved,true);
assert.ok(cancelHaccpReading(state,1,{reason:'Probe identified as defective',responsible:'Alice'}));
assert.equal(haccpReadingStatus(state,first.id).cancelled,true);
assert.equal(verifyHaccpChain(state),true);
assert.equal(updateRecord(state,'temps',0,{value:4}),false);
assert.equal(removeRecord(state,'temps',0),false);
assert.equal(updateRecord(state,'haccpAudit',0,{reason:'changed'}),false);
assert.equal(removeRecord(state,'haccpAudit',0),false);
state.temps[0].value=4;
assert.equal(verifyHaccpChain(state),false);
console.log('HACCP append-only traceability, cancellation, resolution and integrity chain OK');
