import assert from'node:assert/strict';
import{shiftDurationHours,plannedLabor,recipePortfolio,reorderSuggestions,supplierPriceAlerts,supplierPriceOpportunities,purchasePlan,recipeSupplierImpacts,financeTrend,trendSignals,managementOutlook,openHaccpIssues,haccpRoutinePresets,haccpCorrectiveTaskDrafts,serviceBriefingData,equipmentAttention,maintenanceTaskDrafts,dailyManagerReportData,managerReadyActions,onboardingHealth,onboardingNextSteps,suggestedSupplierForStock,managerSnapshot}from'../src/intelligence.js';
globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};
assert.equal(shiftDurationHours('10:00','18:30'),8.5);assert.equal(shiftDurationHours('22:00','02:00'),4);
const state={revenue:0,covers:0,expenses:0,recipeTarget:30,recipeWarning:35,financeHistory:[{date:'2026-09-21',revenue:1000,covers:50,expenses:250}],stock:[{id:'s1',name:'Tomate',unit:'kg',qty:1,price:4,min:2}],deliveries:[],waste:[],stockMoves:[],priceHistory:[{stockId:'s1',product:'Tomate',supplier:'A',unit:'kg',unitPrice:4.4,date:'2026-09-21',recordedAt:'2026-09-21T10:00:00Z'},{stockId:'s1',product:'Tomate',supplier:'A',unit:'kg',unitPrice:4,date:'2026-09-14',recordedAt:'2026-09-14T10:00:00Z'}],team:[{name:'Alex',hourlyRate:25}],shifts:[{employee:'Alex',date:'2026-09-21',start:'10:00',end:'18:00'}],recipes:[{name:'Salade',cost:3,price:12}],temps:[{id:'h1',conforming:false,zone:'Froid',equipment:'Frigo',value:9,min:0,max:5,action:'Isoler',responsible:'Alex',recordedAt:'2026-09-21T08:00:00Z'}],haccpAudit:[],invoices:[{date:'2026-09-20',status:'pending'}],tasks:[['openKitchen',false]],managerTasks:[],preferences:{restaurant:'Demo'},reservations:[]};
assert.equal(reorderSuggestions(state)[0].quantity,3);assert.equal(supplierPriceAlerts(state)[0].changePct,10);assert.equal(suggestedSupplierForStock(state,'s1'),'A');const setupState={preferences:{restaurant:'Demo'},team:[],stock:[],recipes:[],temps:[],financeHistory:[]};assert.equal(onboardingNextSteps(setupState)[0].key,'stock');assert.equal(onboardingNextSteps(setupState)[0].page,'purchases');
const labor=plannedLabor(state,new Date(2026,8,21,12),7);assert.equal(labor.hours,8);assert.equal(labor.cost,200);
assert.equal(recipePortfolio(state).items[0].foodCostPercent,25);assert.equal(openHaccpIssues(state).length,1);assert.equal(haccpRoutinePresets(state)[0].equipment,'Frigo');assert.equal(haccpRoutinePresets(state)[0].responsible,'Alex');const service=serviceBriefingData(state,new Date(2026,8,21,12));assert.equal(service.shifts.length,1);assert.equal(service.haccpIssues,1);assert.equal(service.lowStock,1);assert.equal(service.meaningful,true);state.equipment=[{name:'Four vapeur',location:'Cuisine',serviceDate:'2026-09-25',status:'operational'},{name:'Cellule',location:'Cuisine',serviceDate:'2026-10-20',status:'outOfService'}];assert.equal(equipmentAttention(state,new Date(2026,8,21,12)).length,2);assert.equal(maintenanceTaskDrafts(state,new Date(2026,8,21,12)).length,2);const report=dailyManagerReportData(state,new Date(2026,8,21,18));assert.equal(report.revenue,1000);assert.equal(report.covers,50);assert.equal(report.avgTicket,20);assert.equal(managerReadyActions(state,new Date(2026,8,21,18)).dailyReportNeeded,true);assert.equal(haccpCorrectiveTaskDrafts(state,new Date(2026,8,21,12)).length,1);assert.equal(managerReadyActions(state,new Date(2026,8,21,12)).purchaseOrders.length,1);assert.ok(onboardingHealth(state).score>0);
const plan=purchasePlan(state);assert.equal(plan.estimatedCost,12);assert.equal(plan.groups[0].supplier,'A');
state.priceHistory.push({stockId:'s1',product:'Tomate',supplier:'B',unit:'kg',unitPrice:3.5,date:'2026-09-20',recordedAt:'2026-09-20T10:00:00Z'});const opportunities=supplierPriceOpportunities(state);assert.equal(opportunities[0].bestSupplier,'B');assert.equal(opportunities[0].potentialSaving,2.7);assert.equal(managerReadyActions(state,new Date(2026,8,21,12)).supplierSavings.length,1);const unitState={stock:[{id:'s2',name:'Sauce',unit:'kg',qty:1,price:10,min:2}],deliveries:[],waste:[],stockMoves:[],priceHistory:[{stockId:'s2',product:'Sauce',supplier:'C',unit:'carton',unitPrice:8,date:'2026-09-21',recordedAt:'2026-09-21T12:00:00Z'},{stockId:'s2',product:'Sauce',supplier:'D',unit:'kg',unitPrice:2,date:'2026-09-20',recordedAt:'2026-09-20T12:00:00Z'}]};assert.equal(supplierPriceOpportunities(unitState).length,0);
state.recipes.push({name:'Tomato bowl',ingredients:[{stockId:'s1',quantity:.25,unit:'kg'}],portions:1,yieldPercent:100,price:10,vatRate:0});assert.equal(recipeSupplierImpacts(state)[0].recipe,'Tomato bowl');
const outlook=managementOutlook(state,new Date(2026,8,21,12));assert.equal(outlook.reorderBudget,12);assert.equal(outlook.plannedLaborCost,200);assert.equal(outlook.plannedCommitments,212);
const snapshot=managerSnapshot(state,new Date(2026,8,21,12));assert.ok(snapshot.priorities.some(x=>x.code==='haccp'));assert.ok(snapshot.priorities.some(x=>x.code==='stock'));

const trendState={financeHistory:[
  {date:'2026-09-21',revenue:1200,expenses:300,covers:60},
  {date:'2026-09-14',revenue:1000,expenses:250,covers:50}
]};
const trend=financeTrend(trendState,new Date(2026,8,21,12));assert.equal(trend.current.revenue,1200);assert.equal(trend.previous.revenue,1000);assert.equal(trend.delta.revenuePct,20);assert.equal(trend.current.avgTicket,20);assert.equal(trend.comparable,true);assert.ok(trendSignals(trendState,new Date(2026,8,21,12)).some(x=>x.code==='revenueTrend'));
console.log('Manager intelligence checks passed.');