import assert from 'node:assert/strict';
import {load,importData,stockAvailable,recordWaste,recordStockMovement,localDate} from '../src/store.js';
const data=new Map();
globalThis.localStorage={getItem:key=>data.has(key)?data.get(key):null,setItem:(key,value)=>data.set(key,String(value)),removeItem:key=>data.delete(key)};
const key='remaprohub.v27.state';
data.set(key,'{broken');
data.set(key+'.last-good',JSON.stringify({stock:[{id:'rice',name:'Rice',qty:4,price:2,min:1}],preferences:{currency:'CHF',theme:'taupe',restaurant:'Test'}}));
const recovered=load();
assert.equal(recovered.stock[0].name,'Rice');
assert.equal(data.get(key+'.recovery'),'{broken');
assert.doesNotThrow(()=>JSON.parse(data.get(key)));
const target=load();
const legacy=JSON.stringify({version:25,state:{preferences:{currency:'CHF',theme:'taupe',restaurant:'Legacy'},stock:[{product:'Flour',quantity:5,unitPrice:3}],financeHistory:[]}});
assert.equal(importData(target,legacy),true);
assert.equal(target.stock[0].name,'Flour');
assert.equal(target.stock[0].qty,5);
const stockState={stock:[{id:'flour',name:'Flour',qty:5}],deliveries:[],waste:[],stockMoves:[]};
assert.equal(recordStockMovement(stockState,{stockId:'flour',type:'exit',quantity:6,reason:'Use'}),false);
assert.ok(recordStockMovement(stockState,{stockId:'flour',type:'exit',quantity:3,reason:'Use'}));
assert.equal(stockAvailable(stockState,stockState.stock[0]),2);
assert.equal(recordWaste(stockState,{stockId:'flour',qty:3}),false);
process.env.TZ='Europe/Zurich';
assert.equal(localDate(new Date('2026-09-20T22:30:00Z')),'2026-09-21');
console.log('P0 data recovery, migration and stock guards OK');
