import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const app=readFileSync('src/app.js','utf8'),store=readFileSync('src/store.js','utf8'),cloud=readFileSync('src/cloud.js','utf8'),restored=readFileSync('src/restored.js','utf8');
assert.match(store,/\.last-good/);
assert.match(store,/LEGACY_KEYS/);
assert.match(store,/recordStockMovement/);
assert.match(restored,/recordStockMovement\(s/);
assert.match(app,/id="prepareServiceBriefing"/);assert.match(app,/id="prepareHandover"/);assert.match(app,/id="generateEquipmentTasks"/);assert.match(app,/maintenanceTaskDrafts\(state\)/);assert.match(app,/serviceBriefingText\(draft\)/);assert.match(app,/data-planning-replace/);assert.match(app,/planningReplacementCandidates\(state/);assert.match(app,/dailyRoutineStatus\(state\)/);assert.match(app,/setDailyTaskCompletion\(state/);assert.match(app,/routinesFeedHint/);assert.match(app,/closingControl\(state\)/);assert.match(app,/closingReadyHint/);assert.match(app,/wasteInsights\(state\)/);assert.match(app,/wasteCost7d/);assert.match(app,/serviceReadiness\(state\)/);assert.match(app,/serviceCoverageAlert/);assert.match(restored,/weeklyManagerReviewData\(s\)/);assert.match(restored,/weeklyManagerReview/);assert.match(app,/data-invoice-paid/);assert.match(app,/markInvoicePaid\(state/);assert.match(restored,/id="exportWeeklyManagementPdf"/);assert.match(restored,/weeklyManagementPdf\(s,money\)/);assert.match(app,/planningConflicts\(state\)/);assert.match(app,/planningLeaveConflict/);assert.match(app,/id="generateTrainingTasks"/);assert.match(app,/name="validUntil"/);
assert.doesNotMatch(restored,/type==='exit'\?Math\.max\(0,before-Math\.abs\(q\)\)/);
assert.match(cloud,/RETRYABLE_FUNCTION_STATUS/);
assert.match(cloud,/250\*\(2\*\*attempt\)/);
console.log('P0 UI/static safety guards OK');
