import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const app=readFileSync('src/app.js','utf8');
const css=readFileSync('app/styles.css','utf8');
const sw=readFileSync('app/sw.js','utf8');
const manifest=JSON.parse(readFileSync('app/manifest.json','utf8'));
assert.equal(manifest.display,'standalone');
assert.equal(manifest.scope,'./');
assert.equal(manifest.icons[0].sizes,'192x192');
assert.equal(manifest.icons[1].sizes,'512x512');
assert.match(manifest.icons[2].purpose,/maskable/);
assert.match(css,/body\{font-size:14px/);
assert.match(css,/min-height:48px/);
assert.match(css,/:focus-visible/);
assert.match(css,/prefers-reduced-motion:reduce/);
assert.match(css,/\.sync-badge/);
assert.match(app,/data-sync-status/);
assert.match(app,/role="status"/);
assert.match(app,/aria-live="polite"/);
assert.match(app,/window\.addEventListener\('offline'/);
assert.match(app,/window\.addEventListener\('online'/);
assert.match(app,/networkOnline\(\)/);
assert.match(sw,/caches\.match\(request\)\.then\(cached=>cached\|\|fetch/);
assert.match(sw,/request\.mode==='navigate'/);
console.log('P5 accessibility, installability and offline sync UX OK');
