import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const app=readFileSync('src/app.js','utf8'),restored=readFileSync('src/restored.js','utf8'),legal=readFileSync('src/legal.js','utf8');
assert.match(app,/calculateSwissPayroll\(state/);
assert.match(app,/ccntMinimum\(state/);
assert.match(app,/field_\$\{key\}/);assert.match(app,/set\('avsAiApg',ch\.avsAiApg\)/);
assert.match(app,/set\('employerContributions',ch\.employerContributions\)/);
assert.match(app,/data-payroll-warnings/);
assert.match(restored,/id="payrollSettingsForm"/);
assert.match(restored,/updatePayrollSettings\(s/);
assert.match(restored,/id="swissPayrollCalculator"/);
assert.match(restored,/TODO_VERIFIER_LPP/);
assert.match(restored,/ccntMinimum\(s/);
assert.match(legal,/ccntCategory/);
assert.match(legal,/ccntMinimumSalary/);
console.log('Swiss payroll UI and payslip integration OK');
