import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const pkg=JSON.parse(readFileSync('package.json','utf8'));
const index=readFileSync('app/index.html','utf8');
const workflow=readFileSync('.github/workflows/android.yml','utf8');
const harden=readFileSync('scripts/harden-android.mjs','utf8');
const cloud=readFileSync('src/cloud.js','utf8');
assert.equal(pkg.dependencies['capacitor-secure-storage-plugin'],'0.12.0');
assert.equal(pkg.dependencies['@revenuecat/purchases-capacitor'],'11.3.2');
assert.equal(pkg.dependencies['@capgo/capacitor-native-biometric'],'7.1.13');
assert.match(index,/Content-Security-Policy/);
assert.match(index,/object-src 'none'/);assert.match(index,/frame-src 'none'/);assert.match(index,/connect-src 'self' https:\/\/gkbzawjlmwjweuqckuxm\.supabase\.co/);
assert.doesNotMatch(index,/<script>(?![^>]*src=)/);
assert.match(harden,/compileSdkVersion = 36/);
assert.match(harden,/targetSdkVersion = 36/);
assert.match(harden,/allowBackup="false"/);
assert.match(harden,/usesCleartextTraffic="false"/);
assert.match(harden,/launchMode="singleTop"/);
assert.match(harden,/android\.permission\.USE_BIOMETRIC/);
assert.match(workflow,/workflow_dispatch:/);
const controlledPushTrigger="  push:\n    branches: [rebuild/remaprohub-clean]\n    paths:\n      - '.github/final-build-trigger'\n";
assert.ok(workflow.includes(controlledPushTrigger),'Android build push trigger must stay restricted to the final-build sentinel');
assert.equal((workflow.match(/\n  push:/g)||[]).length,1,'Only one controlled push trigger is allowed');
assert.match(workflow,/bundleRelease/);
assert.match(workflow,/zipalign/);
assert.match(workflow,/-P 16/);
assert.match(cloud,/SecureStoragePlugin/);
assert.match(cloud,/initializeCloudSessionStorage/);
assert.match(cloud,/loadCachedCloudIdentity/);
assert.match(cloud,/requestPasswordReset/);
console.log('Google Play platform hardening and secure session storage OK');
