import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const pkg=JSON.parse(readFileSync('package.json','utf8'));
const index=readFileSync('app/index.html','utf8');
const workflow=readFileSync('.github/workflows/android.yml','utf8');
const harden=readFileSync('scripts/harden-android.mjs','utf8');
const cloud=readFileSync('src/cloud.js','utf8');
assert.equal(pkg.dependencies['capacitor-secure-storage-plugin'],'0.12.0');
assert.equal(pkg.dependencies['@revenuecat/purchases-capacitor'],'13.6.0');
assert.match(index,/Content-Security-Policy/);
assert.match(index,/object-src 'none'/);
assert.doesNotMatch(index,/<script>(?![^>]*src=)/);
assert.match(harden,/compileSdkVersion = 36/);
assert.match(harden,/targetSdkVersion = 36/);
assert.match(harden,/allowBackup="false"/);
assert.match(harden,/usesCleartextTraffic="false"/);
assert.match(harden,/launchMode="singleTop"/);
assert.match(workflow,/workflow_dispatch:/);
assert.doesNotMatch(workflow,/\n\s*push:/);
assert.match(workflow,/bundleRelease/);
assert.match(workflow,/zipalign/);
assert.match(workflow,/-P 16/);
assert.match(cloud,/SecureStoragePlugin/);
assert.match(cloud,/initializeCloudSessionStorage/);
console.log('Google Play platform hardening and secure session storage OK');
