import assert from 'node:assert/strict';
import {recordRecipe,calculateRecipeCost,recipeIngredientCost,removeRecord} from '../src/store.js';
const state={stock:[{id:'flour',name:'Flour',unit:'kg',price:4,qty:10},{id:'milk',name:'Milk',unit:'l',price:2,qty:10}],recipes:[],deliveries:[],waste:[],stockMoves:[]};
assert.equal(recipeIngredientCost(state.stock[0],250,'g'),1);
assert.equal(recipeIngredientCost(state.stock[1],500,'ml'),1);
const recipe=recordRecipe(state,{name:'Pancakes',ingredients:[{stockId:'flour',quantity:250,unit:'g'},{stockId:'milk',quantity:500,unit:'ml'}],portions:4,yieldPercent:80,price:8,vatRate:8.1,allergens:'gluten, milk'});
assert.ok(recipe);
let metrics=calculateRecipeCost(state,recipe);
assert.equal(metrics.rawCost,2);
assert.equal(metrics.totalCost,2.5);
assert.equal(metrics.costPerPortion,0.625);
assert.ok(metrics.netPrice<8);
const before=metrics.costPerPortion;
state.stock[0].price=8;
metrics=calculateRecipeCost(state,recipe);
assert.ok(metrics.costPerPortion>before,'stock price changes recalculate recipe cost');
assert.equal(removeRecord(state,'stock',0),false,'ingredient stock cannot be deleted while linked to a recipe');
assert.equal(recordRecipe(state,{name:'Bad',ingredients:[{stockId:'missing',quantity:1,unit:'kg'}],portions:1,yieldPercent:100,price:10}),false);
console.log('Unlimited recipe costing, unit conversion, yield, VAT and stock linkage OK');
