import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'0.25.0');
assert.equal(JSON.parse(read('capacitor.config.json')).webDir,'app');
assert.equal(pkg.scripts['prepare:web'],'node scripts/prepare-web.mjs');
for(const token of ["fs.cpSync","['src','assets']","runtime-config.js"])assert.ok(read('scripts/prepare-web.mjs').includes(token),token);
assert.ok(read('.gitignore').includes('app/'));
assert.ok(read('.gitignore').includes('android/'));
console.log('ReMaPro POS 0.25 packaging checks passed');
