import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'0.16.0');
assert.equal(pkg.dependencies['@capacitor-community/sqlite'],'7.0.3');
assert.equal(pkg.dependencies['@fedejm/capacitor-esc-pos-printer'],'0.2.3');
assert.equal(JSON.parse(read('capacitor.config.json')).appId,'com.remapro.pos');
const db=read('src/db.js');
for(const token of ['SQLiteConnection','CapacitorSQLite','CREATE TABLE IF NOT EXISTS queue','__sqlite_migrated_v1','IndexedDB fallback'])assert.ok(db.includes(token),token);
assert.doesNotMatch(read('src/cloud.js'),/service[_-]?role/i);
console.log('ReMaPro POS 0.16 smoke checks passed');
