import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {load,stockAvailable,recordWaste,updateWaste,updateRecord,removeRecord} from '../src/store.js';
const app=readFileSync('src/app.js','utf8');
globalThis.localStorage={getItem:()=>JSON.stringify({stock:[{name:'Rice',qty:5,min:3,price:2}]}),setItem(){}};
const state=load(),item=state.stock[0];
assert.ok(item.id,'legacy stock receives stable identifier');
assert.equal(stockAvailable(state,item),5);
state.deliveries.push({stockId:item.id,product:'Rice',qty:4,status:'accepted'});
state.deliveries.push({stockId:item.id,product:'Rice',qty:8,status:'rejected'});
assert.equal(stockAvailable(state,item),9);
updateRecord(state,'deliveries',0,{status:'rejected'});assert.equal(stockAvailable(state,item),5);
updateRecord(state,'deliveries',0,{status:'accepted',qty:2});assert.equal(stockAvailable(state,item),7);
removeRecord(state,'deliveries',0);assert.equal(stockAvailable(state,item),5);
assert.match(app,/name="stockId" required/);
assert.match(app,/name="qty" type="number" min="0\.01"/);
assert.match(app,/stockAvailable\(state,x\)/);
console.log('Stock and delivery reconciliation OK');
state.deliveries[0].status='accepted';state.deliveries[0].qty=4;
state.waste.push({stockId:item.id,product:'Rice',qty:2});
assert.equal(stockAvailable(state,item),7);
updateRecord(state,'waste',0,{qty:3});assert.equal(stockAvailable(state,item),6);
removeRecord(state,'waste',0);assert.equal(stockAvailable(state,item),9);
state.waste.push({product:'Legacy rice',qty:5});assert.equal(stockAvailable(state,item),9);
assert.match(app,/function waste\(\)[\s\S]{0,550}<select name="stockId" required>/);
const movements={stock:[{id:'rice',name:'Rice',qty:5}],deliveries:[],waste:[]};
assert.equal(recordWaste(movements,{stockId:'rice',qty:6}),false);
assert.equal(movements.waste.length,0);
assert.equal(recordWaste(movements,{stockId:'rice',qty:3}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),2);
assert.equal(updateWaste(movements,0,{stockId:'rice',qty:6}),false);
assert.equal(updateWaste(movements,0,{stockId:'rice',qty:4}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),1);
assert.equal(updateWaste(movements,0,{stockId:'missing',qty:1}),false);
assert.equal(movements.waste[0].qty,4);
movements.stock.push({id:'flour',name:'Flour',qty:2});
assert.equal(updateWaste(movements,0,{stockId:'flour',qty:3}),false);
assert.equal(updateWaste(movements,0,{stockId:'flour',qty:2}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),5);
assert.equal(stockAvailable(movements,movements.stock[1]),0);
const protectedStock={stock:[{id:'rice',name:'Rice',qty:2}],deliveries:[{stockId:'rice',qty:5,status:'accepted'}],waste:[{stockId:'rice',qty:6}]};
assert.equal(stockAvailable(protectedStock,protectedStock.stock[0]),1);
assert.equal(updateRecord(protectedStock,'deliveries',0,{status:'rejected'}),false);
assert.equal(updateRecord(protectedStock,'deliveries',0,{qty:3}),false);
assert.equal(removeRecord(protectedStock,'deliveries',0),false);
assert.equal(updateRecord(protectedStock,'stock',0,{qty:0}),false);
assert.equal(updateRecord(protectedStock,'deliveries',0,{qty:4}),true);
assert.equal(stockAvailable(protectedStock,protectedStock.stock[0]),0);
assert.equal(removeRecord(protectedStock,'waste',0),true);
assert.equal(removeRecord(protectedStock,'deliveries',0),true);
