import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {load,stockAvailable,recordWaste,updateWaste,recordDelivery,recordValidated,updateRecord,removeRecord} from '../src/store.js';
const app=readFileSync('src/app.js','utf8');
globalThis.localStorage={getItem:()=>JSON.stringify({stock:[{name:'Rice',qty:5,min:3,price:2}]}),setItem(){}};
const state=load(),item=state.stock[0];
assert.ok(item.id,'legacy stock receives stable identifier');
assert.equal(stockAvailable(state,item),5);
state.deliveries.push({stockId:item.id,product:'Rice',qty:4,status:'accepted'});
state.deliveries.push({stockId:item.id,product:'Rice',qty:8,status:'rejected'});
assert.equal(stockAvailable(state,item),9);
updateRecord(state,'deliveries',0,{status:'rejected'});assert.equal(stockAvailable(state,item),5);
updateRecord(state,'deliveries',0,{status:'accepted',qty:2});assert.equal(stockAvailable(state,item),7);
removeRecord(state,'deliveries',0);assert.equal(stockAvailable(state,item),5);
assert.match(app,/name="stockId" required/);
assert.match(app,/name="qty" type="number" min="0\.01"/);
assert.match(app,/stockAvailable\(state,x\)/);
assert.match(app,/name="reorderTarget"/);
assert.match(app,/id="deliverySupplier"/);assert.match(app,/id="deliveryStock"/);assert.match(app,/suggestedSupplierForStock\(state,deliveryStock\.value\)/);
const targetState={stock:[],deliveries:[],waste:[],stockMoves:[]};const targetItem=recordValidated(targetState,'stock',{name:'Beans',unit:'kg',qty:2,price:4,min:1,reorderTarget:6});assert.ok(targetItem);assert.equal(targetItem.reorderTarget,6);

console.log('Stock and delivery reconciliation OK');
state.deliveries[0].status='accepted';state.deliveries[0].qty=4;
state.waste.push({stockId:item.id,product:'Rice',qty:2});
assert.equal(stockAvailable(state,item),7);
updateRecord(state,'waste',0,{qty:3});assert.equal(stockAvailable(state,item),6);
removeRecord(state,'waste',0);assert.equal(stockAvailable(state,item),9);
state.waste.push({product:'Legacy rice',qty:5});assert.equal(stockAvailable(state,item),9);
assert.match(app,/function waste\(\)[\s\S]{0,550}<select name="stockId" required>/);
const movements={stock:[{id:'rice',name:'Rice',qty:5}],deliveries:[],waste:[]};
assert.equal(recordWaste(movements,{stockId:'rice',qty:6}),false);
assert.equal(movements.waste.length,0);
assert.equal(recordWaste(movements,{stockId:'rice',qty:3}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),2);
assert.equal(updateWaste(movements,0,{stockId:'rice',qty:6}),false);
assert.equal(updateWaste(movements,0,{stockId:'rice',qty:4}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),1);
assert.equal(updateWaste(movements,0,{stockId:'missing',qty:1}),false);
assert.equal(movements.waste[0].qty,4);
movements.stock.push({id:'flour',name:'Flour',qty:2});
assert.equal(updateWaste(movements,0,{stockId:'flour',qty:3}),false);
assert.equal(updateWaste(movements,0,{stockId:'flour',qty:2}),true);
assert.equal(stockAvailable(movements,movements.stock[0]),5);
assert.equal(stockAvailable(movements,movements.stock[1]),0);
const protectedStock={stock:[{id:'rice',name:'Rice',qty:2}],deliveries:[{stockId:'rice',qty:5,status:'accepted'}],waste:[{stockId:'rice',qty:6}]};
assert.equal(stockAvailable(protectedStock,protectedStock.stock[0]),1);
assert.equal(updateRecord(protectedStock,'deliveries',0,{status:'rejected'}),false);
assert.equal(updateRecord(protectedStock,'deliveries',0,{qty:3}),false);
assert.equal(removeRecord(protectedStock,'deliveries',0),false);
assert.equal(updateRecord(protectedStock,'stock',0,{qty:0}),false);
assert.equal(updateRecord(protectedStock,'deliveries',0,{qty:4}),true);
assert.equal(stockAvailable(protectedStock,protectedStock.stock[0]),0);
assert.equal(removeRecord(protectedStock,'waste',0),true);
assert.equal(removeRecord(protectedStock,'deliveries',0),true);
const linkedStock={stock:[{id:'rice',name:'Rice',qty:5}],deliveries:[{stockId:'rice',qty:1,status:'accepted'}],waste:[]};
assert.equal(removeRecord(linkedStock,'stock',0),false);
assert.equal(linkedStock.stock.length,1);
linkedStock.deliveries=[];linkedStock.waste=[{stockId:'rice',qty:1}];
assert.equal(removeRecord(linkedStock,'stock',0),false);
linkedStock.waste=[];
assert.equal(removeRecord(linkedStock,'stock',0),true);
assert.equal(linkedStock.stock.length,0);
const deliveryState={stock:[{id:'rice',name:'Rice',qty:5}],deliveries:[],waste:[]};
assert.equal(recordDelivery(deliveryState,{stockId:'missing',qty:2,status:'accepted'}),false);
assert.equal(recordDelivery(deliveryState,{stockId:'rice',qty:0,status:'accepted'}),false);
assert.equal(recordDelivery(deliveryState,{stockId:'rice',qty:2,status:'unknown'}),false);
assert.ok(recordDelivery(deliveryState,{supplier:'Supplier',stockId:'rice',qty:2,date:'2026-09-18',status:'accepted'}));
assert.equal(stockAvailable(deliveryState,deliveryState.stock[0]),7);
assert.ok(recordDelivery(deliveryState,{supplier:'Supplier',stockId:'rice',qty:3,date:'2026-09-18',status:'rejected'}));
assert.equal(stockAvailable(deliveryState,deliveryState.stock[0]),7);
assert.equal(updateRecord(deliveryState,'deliveries',0,{stockId:'missing'}),false);
assert.match(app,/b\.dataset\.remove==='stock'\)alert\(t\('stockLinked'\)\)/);
