import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../app/styles.css',import.meta.url),'utf8');
assert.ok(app.includes('function hubSidebar()'));
for(const token of ['hub-classic-home','hub-global-search','hub-home-intro','hub-ca-banner','hub-home-section','hub-category-grid']) assert.ok(app.includes(token),token+' missing');
assert.ok(css.includes('V27.12 — Classic mobile-first Hub navigation'));
assert.ok(css.includes('.hub-sidebar'));
assert.ok(css.includes('.hub-category-grid'));
assert.ok(css.includes('@media(max-width:430px)'));
for(const token of ['module-section-nav','data-module-pane','data-module-section','hub-category-grid','Classic mobile-first Hub navigation']) assert.ok(app.includes(token)||css.includes(token),token+' missing');
assert.equal(app.includes('remapro-dashboard-v2'),false,'obsolete dashboard must not return');
assert.equal(app.includes('dashboard-welcome'),false,'obsolete welcome panel must not return');
assert.equal(app.includes('hub-context-panel'),false,'obsolete context panel must not return');
console.log('Hub classic home, mobile clarity and focused module navigation checks passed');
