import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
assert.ok(app.includes("productSearch:''"));
assert.ok(app.includes('function productVisual'));
assert.ok(!app.includes('function productGlyph'));
assert.ok(app.includes('data:image\\/(?:jpeg|png|webp)'));
assert.ok(css.includes('.product-visual>img'));
assert.ok(app.includes('pos-global-search'));
assert.ok(app.includes('service-segments'));
assert.ok(app.includes('payment-primary'));
assert.ok(app.includes('data-service-type-ui'));
assert.ok(css.includes('V0.28 — ReMaPro POS clarity redesign'));
assert.ok(css.includes('.pos-more-menu'));
assert.ok(css.includes('.product-visual'));
assert.ok(css.includes('.cart-tools'));
assert.match(sw,/remapro-pos-shell-v\d{4}[-a-z0-9]*-\d{8}/);
for(const token of ['pos-more-groups','one-task-per-screen operational views','payments{position:sticky']) assert.ok(app.includes(token)||css.includes(token),token+' missing');
console.log('ReMaPro POS clarity redesign checks passed');

assert.ok(css.includes('Current approved ReMaPro POS palette: warm cream'),'approved warm cream POS palette is retained');
assert.ok(css.includes('Approved horizontal category navigation on service screens.'),'approved horizontal category navigation is retained');
assert.ok(css.includes('grid-template-columns:minmax(0,1fr) minmax(320px,380px)'),'tablet service layout keeps products and ticket side by side');
