# Six-language coverage for secondary application modules.
# Keep the release-critical keys here; broader dynamic coverage lives in EXTRA_ROWS/DYNAMIC_ROWS.
MODULE_ROWS = [
('Intégrations','Integrations','Integraciones','Integrationen','Integrazioni','Integrações'),
('Centralise les connexions utilisées par l’établissement.','Centralize the connections used by the establishment.','Centraliza las conexiones utilizadas por el establecimiento.','Verbindungen des Betriebs zentral verwalten.','Centralizza le connessioni utilizzate dalla struttura.','Centralize as ligações utilizadas pelo estabelecimento.'),
('Centralise les connexions utilisées par l\'établissement.','Centralize the connections used by the establishment.','Centraliza las conexiones utilizadas por el establecimiento.','Verbindungen des Betriebs zentral verwalten.','Centralizza le connessioni utilizzate dalla struttura.','Centralize as ligações utilizadas pelo estabelecimento.'),
('Configurer','Configure','Configurar','Konfigurieren','Configura','Configurar'),('Ouvrir Copilot','Open Copilot','Abrir Copilot','Copilot öffnen','Apri Copilot','Abrir Copilot'),('Exporter les données','Export data','Exportar datos','Daten exportieren','Esporta dati','Exportar dados'),
('Catégories & référentiels','Categories & reference data','Categorías y referencias','Kategorien & Stammdaten','Categorie e riferimenti','Categorias e referências'),('+ Catégorie','+ Category','+ Categoría','+ Kategorie','+ Categoria','+ Categoria'),
('Manager Copilot','Manager Copilot','Copilot de gestión','Manager Copilot','Manager Copilot','Copilot de gestão'),('Contexte local actif','Local context active','Contexto local activo','Lokaler Kontext aktiv','Contesto locale attivo','Contexto local ativo'),('Votre question / situation','Your question / situation','Tu pregunta / situación','Ihre Frage / Situation','La tua domanda / situazione','A sua pergunta / situação'),('Analyser','Analyze','Analizar','Analysieren','Analizza','Analisar'),('Briefing du jour','Daily briefing','Briefing del día','Tagesbriefing','Briefing del giorno','Briefing do dia'),
('Commandes & POS','Orders & POS','Pedidos y POS','Bestellungen & POS','Ordini e POS','Encomendas e POS'),('+ Nouvelle commande','+ New order','+ Nuevo pedido','+ Neue Bestellung','+ Nuovo ordine','+ Nova encomenda'),('Table / canal','Table / channel','Mesa / canal','Tisch / Kanal','Tavolo / canale','Mesa / canal'),('Client','Customer','Cliente','Kunde','Cliente','Cliente'),('Statut','Status','Estado','Status','Stato','Estado'),
('Abonnement ReMaPro Hub','ReMaPro Hub subscription','Suscripción ReMaPro Hub','ReMaPro Hub Abonnement','Abbonamento ReMaPro Hub','Subscrição ReMaPro Hub'),('Essai','Trial','Prueba','Testphase','Prova','Teste'),('Choisissez votre formule','Choose your plan','Elige tu plan','Tarif wählen','Scegli il piano','Escolha o seu plano'),('Règles d’accès','Access rules','Reglas de acceso','Zugriffsregeln','Regole di accesso','Regras de acesso'),('Inclus','Included','Incluido','Enthalten','Incluso','Incluído'),('Organisation','Organization','Organización','Organisation','Organizzazione','Organização'),
('Aide & formation','Help & training','Ayuda y formación','Hilfe & Schulung','Aiuto e formazione','Ajuda e formação'),('Guide intégré','Built-in guide','Guía integrada','Integrierter Leitfaden','Guida integrata','Guia integrado'),('Démarrage rapide','Quick start','Inicio rápido','Schnellstart','Avvio rapido','Início rápido'),
('CENTRE DE PARAMÉTRAGE','SETTINGS CENTER','CENTRO DE CONFIGURACIÓN','EINSTELLUNGSZENTRUM','CENTRO IMPOSTAZIONI','CENTRO DE DEFINIÇÕES'),('Profil','Profile','Perfil','Profil','Profilo','Perfil'),('Établissement','Establishment','Establecimiento','Betrieb','Struttura','Estabelecimento'),('Tableau de bord','Dashboard','Panel','Dashboard','Dashboard','Painel'),('Utilisateurs','Users','Usuarios','Benutzer','Utenti','Utilizadores'),('Rôles & accès','Roles & access','Roles y acceso','Rollen & Zugriff','Ruoli e accessi','Funções e acesso'),('Alertes & rappels','Alerts & reminders','Alertas y recordatorios','Warnungen & Erinnerungen','Avvisi e promemoria','Alertas e lembretes'),('Abonnement','Subscription','Suscripción','Abonnement','Abbonamento','Subscrição'),('Plan & facturation','Plan & billing','Plan y facturación','Tarif & Abrechnung','Piano e fatturazione','Plano e faturação'),('Langue de l’application','Application language','Idioma de la aplicación','App-Sprache','Lingua dell’applicazione','Idioma da aplicação'),
('Calcule le coût matière et la marge par recette.','Calculate ingredient cost and margin per recipe.','Calcula el coste de ingredientes y el margen por receta.','Berechnet Wareneinsatz und Marge pro Rezept.','Calcola il costo materia e il margine per ricetta.','Calcula o custo de ingredientes e a margem por receita.'),
('Relevés de température et actions correctives.','Temperature records and corrective actions.','Registros de temperatura y acciones correctivas.','Temperaturaufzeichnungen und Korrekturmaßnahmen.','Registrazioni delle temperature e azioni correttive.','Registos de temperatura e ações corretivas.'),
('Personnel, fonction, taux et statut.','Staff, role, workload and status.','Personal, función, carga de trabajo y estado.','Personal, Funktion, Pensum und Status.','Personale, ruolo, percentuale e stato.','Pessoal, função, carga horária e estado.'),
('Commandes, fournisseurs, réceptions et prix d’achat.','Orders, suppliers, receipts and purchase prices.','Pedidos, proveedores, recepciones y precios de compra.','Bestellungen, Lieferanten, Wareneingänge und Einkaufspreise.','Ordini, fornitori, ricezioni e prezzi di acquisto.','Encomendas, fornecedores, receções e preços de compra.'),
]
