# Additional deterministic six-language UI strings merged by patch_language_runtime.py.
EXTRA_ROWS = [
('Formulaire','Form','Formulario','Formular','Modulo','Formulário'),('Annuler','Cancel','Cancelar','Abbrechen','Annulla','Cancelar'),('Enregistrer','Save','Guardar','Speichern','Salva','Guardar'),('Information','Information','Información','Information','Informazione','Informação'),('Aide à la saisie','Input help','Ayuda de entrada','Eingabehilfe','Aiuto compilazione','Ajuda de preenchimento'),('Fermer','Close','Cerrar','Schließen','Chiudi','Fechar'),
('Passer la démo','Skip demo','Saltar demo','Demo überspringen','Salta demo','Saltar demo'),('Précédent','Previous','Anterior','Zurück','Indietro','Anterior'),('Suivant','Next','Siguiente','Weiter','Avanti','Seguinte'),
('Paramètres','Settings','Configuración','Einstellungen','Impostazioni','Definições'),('Compte','Account','Cuenta','Konto','Account','Conta'),('Infos personnelles','Personal information','Información personal','Persönliche Daten','Informazioni personali','Informações pessoais'),('Général','General','General','Allgemein','Generale','Geral'),('Langue & région','Language & region','Idioma y región','Sprache & Region','Lingua e regione','Idioma e região'),('Notifications','Notifications','Notificaciones','Benachrichtigungen','Notifiche','Notificações'),('Mises à jour','Updates','Actualizaciones','Updates','Aggiornamenti','Atualizações'),('À propos','About','Acerca de','Über','Informazioni','Sobre'),
('Langue','Language','Idioma','Sprache','Lingua','Idioma'),('Format des nombres','Number format','Formato de números','Zahlenformat','Formato numeri','Formato numérico'),('Début de semaine','Start of week','Inicio de semana','Wochenbeginn','Inizio settimana','Início da semana'),('Lundi','Monday','Lunes','Montag','Lunedì','Segunda-feira'),('Dimanche','Sunday','Domingo','Sonntag','Domenica','Domingo'),
('Maintenance','Maintenance','Mantenimiento','Wartung','Manutenzione','Manutenção'),('Équipements, interventions, échéances et suivi.','Equipment, interventions, due dates and tracking.','Equipos, intervenciones, vencimientos y seguimiento.','Geräte, Eingriffe, Termine und Nachverfolgung.','Attrezzature, interventi, scadenze e monitoraggio.','Equipamentos, intervenções, prazos e acompanhamento.'),('+ Intervention','+ Intervention','+ Intervención','+ Eingriff','+ Intervento','+ Intervenção'),('Dernière intervention','Last intervention','Última intervención','Letzter Eingriff','Ultimo intervento','Última intervenção'),('Prochaine échéance','Next due date','Próximo vencimiento','Nächster Termin','Prossima scadenza','Próximo prazo'),
('Briefing équipe','Team briefing','Briefing de equipo','Team-Briefing','Briefing team','Briefing da equipa'),('Prépare le service, les objectifs, risques et priorités.','Prepare service, objectives, risks and priorities.','Prepara el servicio, objetivos, riesgos y prioridades.','Service, Ziele, Risiken und Prioritäten vorbereiten.','Prepara servizio, obiettivi, rischi e priorità.','Prepare o serviço, objetivos, riscos e prioridades.'),('+ Briefing','+ Briefing','+ Briefing','+ Briefing','+ Briefing','+ Briefing'),
('Passation de service','Shift handover','Traspaso de turno','Schichtübergabe','Passaggio consegne','Passagem de turno'),('Transmets les informations essentielles entre équipes.','Share essential information between teams.','Transmite la información esencial entre equipos.','Wichtige Informationen zwischen Teams weitergeben.','Trasmetti le informazioni essenziali tra i team.','Transmita as informações essenciais entre equipas.'),('+ Passation','+ Handover','+ Traspaso','+ Übergabe','+ Passaggio','+ Passagem'),
('RH & salaires','HR & payroll','RR. HH. y nómina','Personal & Lohn','HR e stipendi','RH e salários'),('Dossiers du personnel, paie et formulaires professionnels.','Staff records, payroll and professional forms.','Expedientes de personal, nómina y formularios profesionales.','Personalakten, Lohn und Berufsformulare.','Fascicoli personale, paghe e moduli professionali.','Dossiês de pessoal, salários e formulários profissionais.'),('Créer une fiche de salaire','Create payslip','Crear nómina','Lohnabrechnung erstellen','Crea busta paga','Criar recibo salarial'),('Documents RH enregistrés','Saved HR documents','Documentos RR. HH. guardados','Gespeicherte HR-Dokumente','Documenti HR salvati','Documentos RH guardados'),
('Conformité & juridictions','Compliance & jurisdictions','Cumplimiento y jurisdicciones','Compliance & Rechtsräume','Conformità e giurisdizioni','Conformidade e jurisdições'),('Architecture prête pour des règles par pays/région.','Architecture ready for country/region rules.','Arquitectura preparada para reglas por país/región.','Architektur für Länder-/Regionsregeln vorbereitet.','Architettura pronta per regole per paese/regione.','Arquitetura pronta para regras por país/região.'),
('Contrôle caisse','Cash control','Control de caja','Kassenkontrolle','Controllo cassa','Controlo de caixa'),('Compare le fonds attendu et le comptage réel, avec écart documenté.','Compare expected cash with actual count and document the variance.','Compara el efectivo esperado con el recuento real y documenta la diferencia.','Erwarteten Kassenbestand mit Ist-Zählung vergleichen und Abweichung dokumentieren.','Confronta cassa attesa e conteggio reale documentando lo scarto.','Compare o caixa esperado com a contagem real e documente a diferença.'),('+ Contrôle','+ Check','+ Control','+ Kontrolle','+ Controllo','+ Controlo'),
('KPI hebdomadaire','Weekly KPI','KPI semanal','Wöchentliche KPI','KPI settimanali','KPI semanal'),('Historise les chiffres clés et transforme-les en décisions.','Track key figures over time and turn them into decisions.','Registra los indicadores clave y conviértelos en decisiones.','Kennzahlen historisieren und in Entscheidungen umsetzen.','Storico degli indicatori chiave per trasformarli in decisioni.','Registe os indicadores-chave e transforme-os em decisões.'),('+ Semaine','+ Week','+ Semana','+ Woche','+ Settimana','+ Semana'),
('Réservations & CRM','Reservations & CRM','Reservas y CRM','Reservierungen & CRM','Prenotazioni e CRM','Reservas e CRM'),('Traçabilité','Traceability','Trazabilidad','Rückverfolgbarkeit','Tracciabilità','Rastreabilidade'),('Pertes & déchets','Waste & losses','Pérdidas y residuos','Verluste & Abfälle','Perdite e sprechi','Perdas e resíduos')
]
