export const ACADEMY_CONTENT_VERSION='2026.09.25.1';
export const ACADEMY_LOCALES=['fr','en','de','it'];
const L=(fr,en,de,it)=>({fr,en,de,it});
const S=(fr,en,de,it)=>L(fr,en,de,it);
const T=(id,application,module,roles,title,summary,steps,extra={})=>({
  id,application,module,roles,title,summary,steps,level:extra.level||'beginner',
  offline:extra.offline!==false,version:ACADEMY_CONTENT_VERSION,
  related:extra.related||[],tour:extra.tour||'',media:extra.media||[{type:'video',src:'',poster:'',captions:'',duration:0}],quiz:extra.quiz||null,
  errors:extra.errors||[]
});

export const ACADEMY_TOPICS=[
T('hub-account-security','hub','account',['owner','manager'],L('Compte et sécurité','Account & security','Konto & Sicherheit','Account e sicurezza'),L('Créer, sécuriser et utiliser un compte ReMaPro.','Create, secure and use a ReMaPro account.','ReMaPro-Konto erstellen, sichern und verwenden.','Creare, proteggere e usare un account ReMaPro.'),[
 S('Créer le compte, se connecter et se déconnecter ; utiliser la réinitialisation du mot de passe.','Create the account, sign in/out and use password reset.','Konto erstellen, an-/abmelden und Passwort zurücksetzen.','Creare l’account, accedere/uscire e reimpostare la password.'),
 S('Activer le verrouillage et la biométrie lorsqu’elle est disponible sur l’appareil.','Enable lock and biometrics when supported by the device.','Sperre und Biometrie aktivieren, wenn das Gerät sie unterstützt.','Attivare blocco e biometria quando supportati dal dispositivo.'),
 S('Vérifier les bonnes pratiques : mot de passe individuel, droits minimaux et aucune clé technique partagée.','Use individual passwords, least privilege and never share technical keys.','Individuelle Passwörter, minimale Rechte und keine technischen Schlüssel teilen.','Usare password individuali, privilegi minimi e non condividere chiavi tecniche.')
],{tour:'hub-account'}),
T('hub-organization-users','hub','organization',['owner','manager'],L('Organisation, restaurants et utilisateurs','Organization, restaurants & users','Organisation, Restaurants & Benutzer','Organizzazione, ristoranti e utenti'),L('Structurer les établissements, rôles et permissions.','Structure venues, roles and permissions.','Betriebe, Rollen und Berechtigungen strukturieren.','Strutturare locali, ruoli e permessi.'),[
 S('Créer ou sélectionner un restaurant et comprendre la portée organisation / établissement.','Create/select a restaurant and understand organization vs venue scope.','Restaurant erstellen/auswählen und Organisations-/Betriebsumfang verstehen.','Creare/selezionare un ristorante e capire ambito organizzazione/locale.'),
 S('Ajouter, retirer ou désactiver un utilisateur et lui attribuer un rôle adapté.','Add, remove or disable a user and assign the right role.','Benutzer hinzufügen, entfernen/deaktivieren und passende Rolle zuweisen.','Aggiungere, rimuovere/disattivare un utente e assegnare il ruolo corretto.'),
 S('Limiter les permissions aux modules réellement nécessaires et contrôler les accès multi-restaurants.','Limit permissions to required modules and review multi-restaurant access.','Rechte auf nötige Module begrenzen und Multi-Restaurant-Zugriff prüfen.','Limitare i permessi ai moduli necessari e verificare l’accesso multi-ristorante.')
],{tour:'hub-organization'}),
T('hub-dashboard','hub','dashboard',['owner','manager'],L('Cockpit manager','Manager cockpit','Manager-Cockpit','Cockpit manager'),L('Lire les indicateurs, alertes, tâches, filtres et actions rapides.','Read KPIs, alerts, tasks, filters and quick actions.','Kennzahlen, Warnungen, Aufgaben, Filter und Schnellaktionen lesen.','Leggere KPI, avvisi, attività, filtri e azioni rapide.'),[
 S('Lire le CA du jour sur l’accueil et vérifier l’heure d’actualisation des ventes POS. Préparer le service rassemble ouverture, stock, réservations, équipe et HACCP.','Read daily revenue on Home and check the POS sales refresh time. Prepare the service groups opening, stock, reservations, team and HACCP.','Tagesumsatz auf der Startseite lesen und Aktualisierungszeit der POS-Verkäufe prüfen. Service vorbereiten bündelt Öffnung, Lager, Reservierungen, Team und HACCP.','Leggere il fatturato del giorno nella Home e verificare l’ora di aggiornamento vendite POS. Preparare il servizio riunisce apertura, scorte, prenotazioni, team e HACCP.'),
 S('Prioriser les alertes opérationnelles, HACCP, stock et factures en attente.','Prioritize operational, HACCP, stock and invoice alerts.','Betriebs-, HACCP-, Lager- und Rechnungswarnungen priorisieren.','Dare priorità ad avvisi operativi, HACCP, stock e fatture.'),
 S('Utiliser les actions rapides pour ouvrir directement le bon module.','Use quick actions to jump to the right module.','Schnellaktionen zum passenden Modul verwenden.','Usare le azioni rapide per aprire il modulo corretto.')
],{tour:'hub-dashboard'}),
T('hub-recipes','hub','recipes',['owner','manager'],L('Recettes et food cost','Recipes & food cost','Rezepte & Food Cost','Ricette e food cost'),L('Construire une recette rentable et la publier vers le POS.','Build a profitable recipe and publish it to POS.','Profitables Rezept erstellen und an POS veröffentlichen.','Creare una ricetta redditizia e pubblicarla sul POS.'),[
 S('Créer recette et sous-recettes avec ingrédients, quantités, unités, rendement et portions.','Create recipes/sub-recipes with ingredients, quantities, units, yield and portions.','Rezepte/Unterrezepte mit Zutaten, Mengen, Einheiten, Ausbeute und Portionen erstellen.','Creare ricette/sotto-ricette con ingredienti, quantità, unità, resa e porzioni.'),
 S('Lire coût total, coût par portion, marge, TVA et prix conseillé ; corriger les unités si nécessaire.','Read total/portion cost, margin, VAT and suggested price; fix units when needed.','Gesamt-/Portionskosten, Marge, MwSt. und Preisempfehlung lesen; Einheiten korrigieren.','Leggere costo totale/per porzione, margine, IVA e prezzo consigliato; correggere le unità.'),
 S('Contrôler l’impact des changements de prix fournisseurs puis publier le produit vers ReMaPro POS.','Review supplier price impact then publish the product to ReMaPro POS.','Lieferantenpreisänderungen prüfen und Produkt an ReMaPro POS veröffentlichen.','Verificare l’impatto dei prezzi fornitori e pubblicare il prodotto su ReMaPro POS.')
],{tour:'hub-recipes'}),
T('hub-stock','hub','stock',['owner','manager'],L('Stock, inventaire et mouvements','Stock, inventory & movements','Lager, Inventur & Bewegungen','Stock, inventario e movimenti'),L('Maîtriser stock réel/théorique, seuils, corrections, pertes et valorisation.','Control actual/theoretical stock, thresholds, corrections, waste and valuation.','Ist-/Sollbestand, Schwellen, Korrekturen, Verluste und Bewertung steuern.','Gestire stock reale/teorico, soglie, correzioni, perdite e valorizzazione.'),[
 S('Créer les articles, catégories, unités, stock initial, seuil minimum et cible de réassort.','Create items, categories, units, opening stock, minimum threshold and reorder target.','Artikel, Kategorien, Einheiten, Anfangsbestand, Minimum und Nachbestellziel anlegen.','Creare articoli, categorie, unità, stock iniziale, soglia minima e obiettivo riordino.'),
 S('Enregistrer entrées, sorties, corrections, inventaires et pertes sans masquer l’historique.','Record receipts, issues, corrections, counts and waste without hiding history.','Eingänge, Ausgänge, Korrekturen, Inventuren und Verluste historisch nachvollziehbar erfassen.','Registrare entrate, uscite, correzioni, inventari e perdite mantenendo lo storico.'),
 S('Comparer stock théorique et réel, lire la valorisation et traiter les alertes de rupture.','Compare theoretical vs actual stock, read valuation and handle low-stock alerts.','Soll-/Istbestand vergleichen, Bewertung lesen und Fehlbestandswarnungen behandeln.','Confrontare stock teorico/reale, leggere la valorizzazione e gestire gli avvisi.')
],{tour:'hub-stock'}),
T('hub-delivery-ai','hub','stock',['owner','manager'],L('Scanner une livraison avec l’IA','Scan a delivery with AI','Lieferung mit KI scannen','Scansionare una consegna con IA'),L('Reconnaître plusieurs produits sans modifier le stock avant validation.','Recognize multiple products without changing stock before validation.','Mehrere Produkte erkennen, ohne den Bestand vor Bestätigung zu ändern.','Riconoscere più prodotti senza modificare lo stock prima della convalida.'),[
 S('Prendre/importer plusieurs photos puis lancer l’analyse visuelle, OCR et codes-barres.','Take/import multiple photos then run visual, OCR and barcode analysis.','Mehrere Fotos aufnehmen/importieren und Bild-, OCR- und Barcodeanalyse starten.','Scattare/importare più foto e avviare analisi visiva, OCR e barcode.'),
 S('Vérifier les niveaux vert/orange/rouge, l’association catalogue, quantités, unités et conditionnement.','Check green/orange/red confidence, catalog match, quantities, units and packaging.','Grün/Orange/Rot, Katalogzuordnung, Mengen, Einheiten und Verpackung prüfen.','Verificare confidenza verde/arancio/rosso, catalogo, quantità, unità e confezione.'),
 S('Corriger ou créer un produit, puis valider définitivement : les mouvements stock ne sont créés qu’à cette étape.','Correct/create a product, then validate: stock movements are created only then.','Produkt korrigieren/anlegen, dann bestätigen: Lagerbewegungen entstehen erst dann.','Correggere/creare un prodotto e convalidare: i movimenti stock nascono solo allora.')
]),
T('hub-suppliers-purchases','hub','purchases',['owner','manager'],L('Fournisseurs, achats et livraisons','Suppliers, purchases & deliveries','Lieferanten, Einkauf & Lieferungen','Fornitori, acquisti e consegne'),L('Gérer prix, commandes, réception, écarts et historique fournisseur.','Manage prices, orders, receiving, variances and supplier history.','Preise, Bestellungen, Wareneingang, Abweichungen und Historie verwalten.','Gestire prezzi, ordini, ricezione, scostamenti e storico fornitori.'),[
 S('Créer fournisseurs et conditions, suivre les prix et comparer les opportunités.','Create suppliers/terms, track prices and compare opportunities.','Lieferanten/Konditionen anlegen, Preise verfolgen und Chancen vergleichen.','Creare fornitori/condizioni, seguire prezzi e confrontare opportunità.'),
 S('Préparer commandes et réassorts à partir des besoins stock.','Prepare purchase orders and replenishment from stock needs.','Bestellungen und Nachschub aus Lagerbedarf vorbereiten.','Preparare ordini e riassortimenti dai fabbisogni stock.'),
 S('Réceptionner, noter les écarts/rejets et conserver l’historique de livraison.','Receive goods, record variances/rejections and keep delivery history.','Ware annehmen, Abweichungen/Ablehnungen erfassen und Lieferhistorie behalten.','Ricevere merce, registrare scostamenti/rifiuti e mantenere lo storico.')
]),
T('hub-haccp','hub','haccp',['owner','manager','employee'],L('HACCP et conformité','HACCP & compliance','HACCP & Compliance','HACCP e conformità'),L('Documenter contrôles, non-conformités et actions correctives.','Document checks, non-conformities and corrective actions.','Kontrollen, Abweichungen und Korrekturmaßnahmen dokumentieren.','Documentare controlli, non conformità e azioni correttive.'),[
 S('Effectuer relevés de températures, réception et nettoyage avec responsable et heure.','Record temperatures, receiving and cleaning with responsible person and time.','Temperaturen, Wareneingang und Reinigung mit Verantwortlichem/Zeit erfassen.','Registrare temperature, ricezione e pulizia con responsabile e ora.'),
 S('Traiter une non-conformité avec action corrective, suivi et résolution.','Handle a non-conformity with corrective action, follow-up and resolution.','Abweichung mit Korrekturmaßnahme, Nachverfolgung und Abschluss behandeln.','Gestire una non conformità con azione correttiva, follow-up e chiusura.'),
 S('Consulter historiques, audits, allergènes, rappels et préparer un export d’inspection.','Review histories, audits, allergens, recalls and prepare inspection exports.','Historien, Audits, Allergene, Rückrufe prüfen und Inspektions-Export vorbereiten.','Consultare storico, audit, allergeni, richiami e preparare export per ispezione.')
],{offline:true,tour:'hub-haccp'}),
T('hub-team-planning','hub','team',['owner','manager'],L('Équipe, planning et absences','Team, scheduling & leave','Team, Planung & Abwesenheiten','Team, pianificazione e assenze'),L('Organiser collaborateurs, horaires, absences et coûts.','Organize staff, schedules, leave and labor costs.','Mitarbeiter, Pläne, Abwesenheiten und Personalkosten organisieren.','Organizzare personale, turni, assenze e costi.'),[
 S('Créer les employés, rôles et taux nécessaires au pilotage.','Create employees, roles and rates needed for management.','Mitarbeiter, Rollen und relevante Sätze anlegen.','Creare dipendenti, ruoli e tariffe necessarie.'),
 S('Construire/copy le planning, gérer congés et conflits de présence.','Build/copy schedules and manage leave and staffing conflicts.','Dienstplan erstellen/kopieren, Urlaub und Konflikte verwalten.','Creare/copiare turni e gestire ferie e conflitti.'),
 S('Lire heures planifiées, coûts salariaux et alertes de couverture.','Read planned hours, labor cost and coverage alerts.','Geplante Stunden, Personalkosten und Abdeckungswarnungen lesen.','Leggere ore pianificate, costo del personale e avvisi di copertura.')
],{tour:'hub-team'}),
T('hub-hr-documents','hub','documents',['owner','manager'],L('RH, contrats et documents','HR, contracts & documents','HR, Verträge & Dokumente','HR, contratti e documenti'),L('Produire et conserver les documents RH et opérationnels.','Create and keep HR and operational documents.','HR- und Betriebsdokumente erstellen und verwalten.','Creare e conservare documenti HR e operativi.'),[
 S('Créer contrats CDI/extra, fiches de paie, attestations, certificats et avenants disponibles.','Create employment/extra contracts, payslips, attestations, certificates and amendments.','Arbeits-/Aushilfsverträge, Lohnabrechnungen, Bescheinigungen und Änderungen erstellen.','Creare contratti, extra, buste paga, attestati, certificati e modifiche.'),
 S('Renseigner les champs légaux et vérifier le pays/canton avant édition.','Fill legal fields and verify country/canton before issuing.','Rechtsfelder ausfüllen und Land/Kanton vor Ausgabe prüfen.','Compilare i campi legali e verificare paese/cantone prima dell’emissione.'),
 S('Utiliser exports, historique et documents HACCP/gestion selon le besoin.','Use exports, history and HACCP/management documents as needed.','Exporte, Historie und HACCP/Management-Dokumente nutzen.','Usare export, storico e documenti HACCP/gestione secondo necessità.')
]),
T('hub-finance','hub','finance',['owner','manager'],L('Finance et pilotage','Finance & management','Finanzen & Steuerung','Finanza e controllo'),L('Suivre CA, dépenses, paiements et rapports.','Track revenue, expenses, payments and reports.','Umsatz, Ausgaben, Zahlungen und Berichte verfolgen.','Monitorare ricavi, spese, pagamenti e report.'),[
 S('Saisir et analyser chiffre d’affaires, couverts, ticket moyen et dépenses par période.','Enter/analyze revenue, covers, average check and expenses by period.','Umsatz, Gäste, Durchschnittsbon und Ausgaben je Zeitraum erfassen/analysieren.','Inserire/analizzare ricavi, coperti, scontrino medio e spese per periodo.'),
 S('Contrôler la ventilation des moyens de paiement et les écarts de caisse lorsque disponibles.','Review payment-method breakdown and cash variances when available.','Zahlungsarten und Kassendifferenzen prüfen, sofern verfügbar.','Controllare metodi di pagamento e differenze di cassa quando disponibili.'),
 S('Lire rapports, comparaisons, KPI hebdomadaires et exports avant décision.','Read reports, comparisons, weekly KPIs and exports before decisions.','Berichte, Vergleiche, Wochen-KPIs und Exporte vor Entscheidungen lesen.','Leggere report, confronti, KPI settimanali ed export prima di decidere.')
],{tour:'hub-finance'}),
T('hub-ai','hub','ai',['owner','manager'],L('ReMaPro AI','ReMaPro AI','ReMaPro AI','ReMaPro AI'),L('Utiliser l’assistant comme copilote sans déléguer les validations sensibles.','Use AI as a copilot without delegating sensitive approvals.','KI als Copilot nutzen, sensible Freigaben aber selbst behalten.','Usare l’IA come copilota senza delegare approvazioni sensibili.'),[
 S('Poser une question précise et comprendre quelles données du restaurant alimentent le contexte.','Ask precise questions and understand which restaurant data supplies context.','Präzise fragen und verstehen, welche Restaurantdaten den Kontext bilden.','Porre domande precise e capire quali dati del ristorante formano il contesto.'),
 S('Différencier observation, recommandation et action réellement validée dans l’application.','Distinguish observation, recommendation and an actually confirmed action.','Beobachtung, Empfehlung und tatsächlich bestätigte Aktion unterscheiden.','Distinguere osservazione, raccomandazione e azione realmente convalidata.'),
 S('Vérifier les limites : pas d’invention de données, validation humaine et règles locales à contrôler.','Respect limits: no invented data, human validation and local-rule verification.','Grenzen beachten: keine erfundenen Daten, menschliche Freigabe, lokale Regeln prüfen.','Rispettare i limiti: niente dati inventati, convalida umana e norme locali da verificare.')
]),
T('hub-pos-admin','hub','posAdmin',['owner','manager'],L('Administration ReMaPro POS','ReMaPro POS administration','ReMaPro POS Verwaltung','Amministrazione ReMaPro POS'),L('Configurer appareils, opérateurs, permissions, terminaux, imprimantes et synchronisation.','Configure devices, operators, permissions, terminals, printers and sync.','Geräte, Bediener, Rechte, Terminals, Drucker und Sync konfigurieren.','Configurare dispositivi, operatori, permessi, terminali, stampanti e sincronizzazione.'),[
 S('Activer le restaurant POS et publier le catalogue depuis le Hub.','Enable POS for the restaurant and publish the catalog from Hub.','POS fürs Restaurant aktivieren und Katalog aus Hub veröffentlichen.','Attivare POS per il ristorante e pubblicare il catalogo dal Hub.'),
 S('Créer opérateurs, PIN et permissions ; associer appareils et limiter les actions manager.','Create operators, PINs and permissions; associate devices and manager actions.','Bediener, PINs, Rechte und Geräte verwalten; Manager-Aktionen begrenzen.','Creare operatori, PIN e permessi; associare dispositivi e azioni manager.'),
 S('Configurer stations cuisine/bar, imprimantes, terminaux et contrôler la synchronisation/rapports.','Configure kitchen/bar stations, printers, terminals and review sync/reports.','Küche/Bar, Drucker, Terminals konfigurieren und Sync/Berichte prüfen.','Configurare cucina/bar, stampanti, terminali e controllare sync/report.')
],{tour:'hub-pos-admin'}),
T('hub-pos-layout','hub','posAdmin',['owner','manager'],L('Implantation de caisse','POS layout editor','Kassenlayout','Layout cassa'),L('Construire et publier l’implantation utilisée sur les tablettes POS.','Build and publish the layout used by POS tablets.','Layout für POS-Tablets erstellen und veröffentlichen.','Creare e pubblicare il layout usato dai tablet POS.'),[
 S('Créer pages, catégories/sous-catégories, touches, favoris, couleurs, tailles et ordre.','Create pages, categories/subcategories, keys, favorites, colors, sizes and order.','Seiten, Kategorien, Tasten, Favoriten, Farben, Größen und Reihenfolge erstellen.','Creare pagine, categorie, tasti, preferiti, colori, dimensioni e ordine.'),
 S('Gérer produits masqués/indisponibles, modificateurs, cuissons, suppléments et sans ingrédient.','Manage hidden/unavailable products, modifiers, cooking, extras and no-ingredient choices.','Verborgene/nicht verfügbare Produkte, Modifikatoren, Garstufen und Extras verwalten.','Gestire prodotti nascosti/non disponibili, modificatori, cotture ed extra.'),
 S('Créer menus/compositions, prévisualiser, publier une version et revenir à une version antérieure selon disponibilité.','Create menus/compositions, preview, publish a version and restore an earlier version when available.','Menüs erstellen, Vorschau, Version veröffentlichen und ggf. ältere Version wiederherstellen.','Creare menu, anteprima, pubblicare una versione e ripristinare versioni precedenti se disponibile.')
],{tour:'hub-pos-layout'}),
T('hub-reservations-customers','hub','reservations',['owner','manager'],L('Réservations, clients et fidélité','Reservations, customers & loyalty','Reservierungen, Kunden & Treue','Prenotazioni, clienti e fedeltà'),L('Centraliser réservations, clients et suivi fidélité.','Centralize reservations, customers and loyalty.','Reservierungen, Kunden und Treue zentral verwalten.','Centralizzare prenotazioni, clienti e fedeltà.'),[
 S('Créer, confirmer, annuler ou marquer les réservations/no-show et surveiller les confirmations.','Create, confirm, cancel or mark reservations/no-shows and monitor confirmations.','Reservierungen erstellen/bestätigen/stornieren/no-show markieren und Bestätigungen überwachen.','Creare, confermare, annullare o segnare no-show e controllare conferme.'),
 S('Maintenir la fiche client, notes utiles et coordonnées pertinentes.','Maintain customer records, useful notes and relevant contact details.','Kundendaten, Notizen und relevante Kontaktdaten pflegen.','Mantenere scheda cliente, note utili e contatti pertinenti.'),
 S('Utiliser le suivi fidélité sans mélanger les données entre restaurants.','Use loyalty tracking without mixing data between restaurants.','Treue verfolgen, ohne Daten zwischen Restaurants zu vermischen.','Usare la fedeltà senza mescolare dati tra ristoranti.')
]),
T('hub-compliance-ops','hub','operations',['owner','manager'],L('Exploitation, maintenance et conformité','Operations, maintenance & compliance','Betrieb, Wartung & Compliance','Operazioni, manutenzione e conformità'),L('Suivre incidents, équipements, maintenance, audits, rappels et tâches.','Track incidents, equipment, maintenance, audits, recalls and tasks.','Vorfälle, Geräte, Wartung, Audits, Rückrufe und Aufgaben verfolgen.','Seguire incidenti, attrezzature, manutenzione, audit, richiami e attività.'),[
 S('Utiliser checklists, briefing, passation, tâches et alertes pour le service quotidien.','Use checklists, briefings, handover, tasks and alerts for daily service.','Checklisten, Briefings, Übergabe, Aufgaben und Warnungen im Alltag nutzen.','Usare checklist, briefing, passaggio consegne, attività e avvisi quotidiani.'),
 S('Enregistrer incidents, équipements, échéances de maintenance et actions associées.','Record incidents, equipment, maintenance due dates and related actions.','Vorfälle, Geräte, Wartungsfristen und Maßnahmen erfassen.','Registrare incidenti, attrezzature, scadenze manutenzione e azioni.'),
 S('Gérer audits, rappels produits, allergènes, nettoyage et preuves de conformité.','Manage audits, recalls, allergens, cleaning and compliance evidence.','Audits, Rückrufe, Allergene, Reinigung und Nachweise verwalten.','Gestire audit, richiami, allergeni, pulizia e prove di conformità.')
]),
T('hub-settings-subscription','hub','settings',['owner'],L('Paramètres et abonnement','Settings & subscription','Einstellungen & Abo','Impostazioni e abbonamento'),L('Configurer langue, apparence, notifications, sauvegarde et formule.','Configure language, appearance, notifications, backup and plan.','Sprache, Darstellung, Benachrichtigungen, Backup und Tarif konfigurieren.','Configurare lingua, aspetto, notifiche, backup e piano.'),[
 S('Régler langue, thème, couleur, densité et navigation selon l’appareil.','Set language, theme, color, density and navigation for the device.','Sprache, Theme, Farbe, Dichte und Navigation fürs Gerät einstellen.','Impostare lingua, tema, colore, densità e navigazione per il dispositivo.'),
 S('Configurer notifications, sécurité, synchronisation cloud, export/import et sauvegarde.','Configure notifications, security, cloud sync, export/import and backup.','Benachrichtigungen, Sicherheit, Cloud-Sync, Export/Import und Backup konfigurieren.','Configurare notifiche, sicurezza, sync cloud, export/import e backup.'),
 S('Comprendre essai, formule Standard/Pro et limites multi-restaurants/utilisateurs.','Understand trial, Standard/Pro plans and multi-restaurant/user limits.','Testphase, Standard/Pro und Multi-Restaurant-/Benutzergrenzen verstehen.','Capire prova, piani Standard/Pro e limiti multi-ristorante/utenti.')
]),

T('pos-first-use','pos','setup',['owner','manager','server'],L('Première utilisation POS','POS first use','POS-Erstnutzung','Primo utilizzo POS'),L('Installer, se connecter, choisir le restaurant et synchroniser.','Install, sign in, choose restaurant and sync.','Installieren, anmelden, Restaurant wählen und synchronisieren.','Installare, accedere, scegliere ristorante e sincronizzare.'),[
 S('Installer l’application, se connecter avec le compte ReMaPro et choisir le restaurant autorisé.','Install the app, sign in with ReMaPro and choose an authorized restaurant.','App installieren, mit ReMaPro anmelden und autorisiertes Restaurant wählen.','Installare l’app, accedere con ReMaPro e scegliere un ristorante autorizzato.'),
 S('Laisser l’appareil s’enregistrer puis effectuer la synchronisation initiale du catalogue, tables et réglages.','Let the device register then run initial catalog/table/settings sync.','Gerät registrieren lassen, dann Katalog, Tische und Einstellungen initial synchronisieren.','Registrare il dispositivo e sincronizzare catalogo, tavoli e impostazioni.'),
 S('Vérifier l’indicateur En ligne/Synchronisé avant le premier service.','Check Online/Synchronized before first service.','Vor dem ersten Service Online/Synchronisiert prüfen.','Verificare Online/Sincronizzato prima del primo servizio.')
],{offline:true,tour:'pos-setup'}),
T('pos-operator','pos','team',['manager','server','kitchen'],L('Opérateur, PIN et permissions','Operator, PIN & permissions','Bediener, PIN & Rechte','Operatore, PIN e permessi'),L('Changer d’opérateur en respectant les droits attribués.','Switch operators while respecting assigned permissions.','Bediener wechseln und zugewiesene Rechte einhalten.','Cambiare operatore rispettando i permessi assegnati.'),[
 S('Sélectionner son profil et saisir son PIN personnel.','Select your profile and enter your personal PIN.','Eigenes Profil wählen und persönlichen PIN eingeben.','Selezionare il profilo e inserire il PIN personale.'),
 S('Changer d’opérateur lors du changement de personne, sans partager le PIN.','Switch operator when staff changes and never share PINs.','Bei Personalwechsel Bediener wechseln und PIN nicht teilen.','Cambiare operatore al cambio persona e non condividere il PIN.'),
 S('Les remboursements, réglages et autres actions sensibles restent soumis aux droits manager.','Refunds, settings and sensitive actions remain manager-restricted.','Erstattungen, Einstellungen und sensible Aktionen bleiben Manager-beschränkt.','Rimborsi, impostazioni e azioni sensibili restano riservati ai manager.')
],{offline:true}),
T('pos-cash-session','pos','cash',['manager','server'],L('Session de caisse','Cash session','Kassensitzung','Sessione cassa'),L('Ouvrir, compter et clôturer la caisse avec traçabilité.','Open, count and close cash with traceability.','Kasse nachvollziehbar öffnen, zählen und schließen.','Aprire, contare e chiudere la cassa con tracciabilità.'),[
 S('Ouvrir la caisse avec le fond de caisse réel et vérifier la date de service.','Open cash with the real float and verify business date.','Kasse mit echtem Wechselgeld öffnen und Geschäftstag prüfen.','Aprire la cassa con fondo reale e verificare la data servizio.'),
 S('Pendant le service, garder la session ouverte et traiter les notes avant clôture.','Keep session open during service and settle open checks before closing.','Sitzung offen halten und offene Rechnungen vor Abschluss bearbeiten.','Tenere aperta la sessione e chiudere i conti prima della chiusura.'),
 S('Ouvrir Clôturer la caisse, traiter les notes, brouillons, paiements terminal et envois en attente. Revenir en ligne pour actualiser le récapitulatif.','Open Close till and resolve bills, drafts, terminal payments and pending uploads. Reconnect to refresh the summary.','Kassenabschluss öffnen; Rechnungen, Entwürfe, Terminalzahlungen und Übertragungen bearbeiten. Online die Übersicht aktualisieren.','Aprire Chiudi cassa e risolvere conti, bozze, pagamenti terminale e invii in attesa. Ricollegarsi per aggiornare il riepilogo.'),
 S('Choisir Compter et clôturer, saisir les espèces réelles puis consulter le montant attendu et l’écart après confirmation du serveur. Le récapitulatif des paiements concerne toutes les caisses du restaurant.','Choose Count and close, enter the actual cash, then review expected cash and the difference after server confirmation. The payment summary covers all restaurant tills.','Zählen und abschliessen wählen, Ist-Bargeld erfassen und nach Serverbestätigung Sollbestand und Differenz prüfen. Die Zahlungsübersicht umfasst alle Restaurantkassen.','Scegliere Contare e chiudere, inserire i contanti reali e controllare importo atteso e differenza dopo la conferma del server. Il riepilogo pagamenti include tutte le casse del ristorante.')
],{offline:true,tour:'pos-cash'}),
T('pos-floor','pos','floor',['manager','server'],L('Plan de salle et tables','Floor plan & tables','Tischplan & Tische','Sala e tavoli'),L('Gérer tables, couverts, notes et transferts.','Manage tables, covers, checks and transfers.','Tische, Gäste, Rechnungen und Transfers verwalten.','Gestire tavoli, coperti, conti e trasferimenti.'),[
 S('Ouvrir une table libre, saisir couverts et retrouver les notes sans table.','Open a free table, enter covers and find unassigned checks.','Freien Tisch öffnen, Gäste erfassen und nicht zugeordnete Rechnungen finden.','Aprire un tavolo libero, inserire coperti e trovare conti senza tavolo.'),
 S('Reprendre une note, transférer vers une autre table et gérer séparation/regroupement quand disponible.','Resume a check, transfer it and use split/merge features when available.','Rechnung fortsetzen, übertragen und ggf. teilen/zusammenführen.','Riprendere un conto, trasferirlo e usare separazione/unione se disponibile.'),
 S('Ne jamais fermer une table tant que le paiement n’est pas réellement terminé.','Do not close a table until payment is actually complete.','Tisch erst schließen, wenn Zahlung wirklich abgeschlossen ist.','Non chiudere il tavolo finché il pagamento non è realmente concluso.')
],{offline:true,tour:'pos-floor'}),
T('pos-ordering','pos','sale',['server','manager'],L('Prise de commande','Order entry','Bestellaufnahme','Presa comanda'),L('Saisir une commande rapidement et proprement.','Enter orders quickly and accurately.','Bestellungen schnell und sauber erfassen.','Inserire ordini rapidamente e correttamente.'),[
 S('Naviguer pages, catégories, favoris et touches produits ; ajouter quantité ou article libre.','Navigate pages, categories, favorites and product keys; add quantity or open item.','Seiten, Kategorien, Favoriten und Produkttasten nutzen; Mengen/freie Artikel hinzufügen.','Navigare pagine, categorie, preferiti e tasti; aggiungere quantità o articolo libero.'),
 S('Corriger/supprimer avant envoi, ajouter notes et distinguer les ajouts après envoi.','Correct/delete before sending, add notes and identify additions after send.','Vor Versand korrigieren/löschen, Notizen hinzufügen und Nachträge erkennen.','Correggere/eliminare prima dell’invio, aggiungere note e distinguere aggiunte successive.'),
 S('Enregistrer la note ou l’envoyer en production selon le type de service.','Save the check or send to production depending on service type.','Rechnung speichern oder je Serviceart an Produktion senden.','Salvare il conto o inviarlo in produzione secondo il servizio.')
],{offline:true,tour:'pos-sale'}),
T('pos-modifiers-menus','pos','sale',['server','manager'],L('Modificateurs et menus','Modifiers & menus','Modifikatoren & Menüs','Modificatori e menu'),L('Appliquer cuisson, accompagnements, suppléments et compositions.','Apply cooking, sides, extras and menu compositions.','Garstufen, Beilagen, Extras und Menüs anwenden.','Applicare cotture, contorni, extra e composizioni.'),[
 S('Répondre à tous les choix obligatoires avant ajout au panier.','Complete all required choices before adding to cart.','Alle Pflichtauswahlen vor dem Warenkorb abschließen.','Completare tutte le scelte obbligatorie prima del carrello.'),
 S('Choisir cuisson, accompagnement, supplément, sans ingrédient et notes dans les limites min/max.','Choose cooking, sides, extras, no-ingredient and notes within min/max limits.','Garstufe, Beilage, Extras, ohne Zutat und Notizen innerhalb Min/Max wählen.','Scegliere cottura, contorni, extra, senza ingrediente e note entro min/max.'),
 S('Vérifier le prix final et les choix de menu avant envoi cuisine/bar.','Verify final price and menu choices before kitchen/bar send.','Endpreis und Menüwahl vor Versand an Küche/Bar prüfen.','Verificare prezzo finale e scelte menu prima dell’invio cucina/bar.')
],{offline:true}),
T('pos-production','pos','production',['kitchen','manager','server'],L('Production cuisine / bar','Kitchen / bar production','Küche / Bar Produktion','Produzione cucina / bar'),L('Suivre les tickets et états de préparation.','Track tickets and preparation statuses.','Tickets und Produktionsstatus verfolgen.','Seguire ticket e stati di preparazione.'),[
 S('Filtrer Tout, Cuisine ou Bar et lire quantités, notes, modificateurs et station.','Filter All, Kitchen or Bar and read quantities, notes, modifiers and station.','Alle/Küche/Bar filtern und Mengen, Notizen, Modifikatoren und Station lesen.','Filtrare Tutto/Cucina/Bar e leggere quantità, note, modificatori e stazione.'),
 S('Faire progresser Sent → Preparing → Ready → Served uniquement lorsque l’étape est réelle.','Advance Sent → Preparing → Ready → Served only when true.','Sent → Preparing → Ready → Served nur bei realem Status fortschalten.','Avanzare Sent → Preparing → Ready → Served solo quando reale.'),
 S('Réimprimer le ticket de production au besoin et respecter le routage par station.','Reprint production ticket when needed and respect station routing.','Produktionsticket bei Bedarf nachdrucken und Stationsrouting beachten.','Ristampare ticket produzione se necessario e rispettare il routing.')
],{offline:true,tour:'pos-production'}),
T('pos-payments','pos','payment',['server','manager'],L('Paiements','Payments','Zahlungen','Pagamenti'),L('Encaisser en espèces, carte, TWINT ou moyen externe sans double débit.','Take cash, card, TWINT or external payment without double charging.','Bar, Karte, TWINT oder extern kassieren ohne Doppelbelastung.','Incassare contanti, carta, TWINT o esterno senza doppio addebito.'),[
 S('Vérifier total, moyen de paiement et pourboire avant confirmation.','Verify total, payment method and tip before confirmation.','Summe, Zahlungsart und Trinkgeld vor Bestätigung prüfen.','Verificare totale, metodo e mancia prima della conferma.'),
 S('Pour carte/TWINT externe, confirmer dans ReMaPro seulement après succès réel du terminal.','For external card/TWINT, confirm in ReMaPro only after terminal success.','Externe Karte/TWINT in ReMaPro erst nach echtem Terminal-Erfolg bestätigen.','Per carta/TWINT esterno, confermare in ReMaPro solo dopo successo terminale.'),
 S('En cas d’échec ou paiement en attente, ne pas relancer aveuglément : vérifier le statut et le ticket.','On failed/pending payment, check status/receipt before retrying.','Bei Fehler/ausstehender Zahlung Status/Beleg prüfen, nicht blind wiederholen.','In caso di errore/in attesa, verificare stato/scontrino prima di riprovare.')
],{offline:true,tour:'pos-payment'}),
T('pos-split-payments','pos','payment',['server','manager'],L('Paiements fractionnés','Split payments','Geteilte Zahlungen','Pagamenti frazionati'),L('Partager par montant, article ou personne et suivre le reste dû.','Split by amount, item or person and track remaining due.','Nach Betrag, Artikel oder Person teilen und Restbetrag verfolgen.','Dividere per importo, articolo o persona e seguire il residuo.'),[
 S('Choisir partage par montants, par articles ou encaissement progressif par personne.','Choose amount split, item split or progressive per-person payment.','Betrags-, Artikel- oder progressive Personenteilung wählen.','Scegliere divisione per importi, articoli o progressiva per persona.'),
 S('Contrôler chaque part, moyen de paiement et montant restant avant la suivante.','Check each share, payment method and remaining amount before the next.','Jeden Anteil, Zahlungsart und Restbetrag vor dem nächsten prüfen.','Controllare ogni quota, metodo e residuo prima della successiva.'),
 S('Imprimer si nécessaire les tickets fractionnés liés au ticket maître.','Print split receipts linked to the master receipt when needed.','Bei Bedarf Teilbelege zum Hauptbeleg drucken.','Stampare se necessario gli scontrini frazionati legati al principale.')
],{offline:true}),
T('pos-tickets','pos','tickets',['server','manager'],L('Tickets et historique','Receipts & history','Belege & Historie','Scontrini e storico'),L('Retrouver, imprimer et comprendre les tickets.','Find, print and understand receipts.','Belege finden, drucken und verstehen.','Trovare, stampare e capire gli scontrini.'),[
 S('Retrouver numéro, date, table/service, total et moyens de paiement.','Find number, date, table/service, total and payment methods.','Nummer, Datum, Tisch/Service, Summe und Zahlungsarten finden.','Trovare numero, data, tavolo/servizio, totale e pagamenti.'),
 S('Imprimer ticket maître ou ticket d’une part fractionnée sans recréer la vente.','Print master or split receipt without recreating the sale.','Haupt-/Teilbeleg drucken, ohne Verkauf neu zu erzeugen.','Stampare scontrino principale/frazionato senza ricreare la vendita.'),
 S('Utiliser l’historique pour vérifier un paiement avant remboursement ou support.','Use history to verify a payment before refund/support.','Historie vor Erstattung/Support zur Zahlungsprüfung nutzen.','Usare lo storico per verificare un pagamento prima di rimborso/supporto.')
],{offline:true}),
T('pos-refunds','pos','tickets',['manager'],L('Remboursements','Refunds','Erstattungen','Rimborsi'),L('Rembourser totalement ou partiellement avec traçabilité.','Refund fully or partially with traceability.','Vollständig/teilweise nachvollziehbar erstatten.','Rimborsare totalmente o parzialmente con tracciabilità.'),[
 S('Ouvrir le ticket d’origine et choisir remboursement total ou partiel.','Open original receipt and choose full or partial refund.','Originalbeleg öffnen und Voll-/Teilerstattung wählen.','Aprire lo scontrino originale e scegliere rimborso totale/parziale.'),
 S('Pour un prestataire externe, attendre/valider le remboursement externe avant clôture ReMaPro.','For an external provider, confirm external refund before closing in ReMaPro.','Bei externem Anbieter Erstattung extern bestätigen, bevor ReMaPro abschließt.','Con provider esterno, confermare rimborso esterno prima di chiudere ReMaPro.'),
 S('Contrôler l’historique et ne jamais supprimer une vente payée.','Review audit history and never delete a paid sale.','Historie prüfen und bezahlten Verkauf nie löschen.','Controllare lo storico e non eliminare mai una vendita pagata.')
]),
T('pos-offline-sync','pos','sync',['manager','server'],L('Mode hors ligne et synchronisation','Offline & sync','Offline & Synchronisation','Offline e sincronizzazione'),L('Continuer le service avec le cache local puis resynchroniser proprement.','Continue service from local cache and resync safely.','Mit lokalem Cache weiterarbeiten und sicher synchronisieren.','Continuare con cache locale e risincronizzare in sicurezza.'),[
 S('Sans réseau, utiliser les données déjà synchronisées et surveiller le compteur “en attente”.','Offline, use cached data and watch the pending counter.','Offline Cache-Daten nutzen und Warteschlange beobachten.','Offline usare dati in cache e controllare gli elementi in attesa.'),
 S('Au retour en ligne, laisser la file se vider ; ne pas dupliquer une action déjà en attente.','When online returns, let queue drain; do not duplicate pending actions.','Nach Rückkehr online Warteschlange abarbeiten lassen; Aktionen nicht doppeln.','Al ritorno online lasciare svuotare la coda; non duplicare azioni pendenti.'),
 S('En cas de conflit/opérateur, se réauthentifier et relancer depuis l’écran Synchronisation.','On conflict/operator issue, reauthenticate and retry from Sync.','Bei Konflikt/Bedienerproblem neu authentifizieren und über Sync erneut versuchen.','In caso di conflitto/operatore, riautenticare e riprovare da Sincronizzazione.')
],{offline:true,tour:'pos-sync'}),
T('pos-printers','pos','hardware',['manager'],L('Imprimantes ESC/POS','ESC/POS printers','ESC/POS-Drucker','Stampanti ESC/POS'),L('Découvrir, configurer, tester et router les imprimantes.','Discover, configure, test and route printers.','Drucker finden, konfigurieren, testen und routen.','Scoprire, configurare, testare e instradare stampanti.'),[
 S('Scanner/découvrir les imprimantes disponibles puis créer un profil.','Scan/discover printers then create a profile.','Drucker suchen und Profil erstellen.','Scansionare/scoprire stampanti e creare un profilo.'),
 S('Choisir rôle ticket/cuisine/bar, paramètres réseau/native et tester avant service.','Choose receipt/kitchen/bar role, network/native settings and test before service.','Beleg/Küche/Bar, Netzwerk/nativ wählen und vor Service testen.','Scegliere ruolo scontrino/cucina/bar, rete/nativo e testare prima del servizio.'),
 S('Si impression échoue, garder la vente intacte et utiliser le dépannage guidé.','If printing fails, keep sale intact and use guided troubleshooting.','Bei Druckfehler Verkauf intakt lassen und Fehlerhilfe nutzen.','Se la stampa fallisce, mantenere la vendita e usare il troubleshooting.')
],{offline:true}),
T('pos-terminals','pos','hardware',['manager'],L('Terminaux de paiement','Payment terminals','Zahlungsterminals','Terminali di pagamento'),L('Configurer profils et états sans exposer de secrets.','Configure profiles/status without exposing secrets.','Profile/Status konfigurieren, ohne Secrets offenzulegen.','Configurare profili/stati senza esporre segreti.'),[
 S('Créer le profil terminal/prestataire et vérifier devise/capacités.','Create terminal/provider profile and verify currency/capabilities.','Terminal-/Providerprofil erstellen und Währung/Fähigkeiten prüfen.','Creare profilo terminale/provider e verificare valuta/capacità.'),
 S('Lire les états Non configuré/Configuré/En ligne/Hors ligne/Erreur.','Read Not configured/Configured/Online/Offline/Error states.','Status Nicht konfiguriert/Konfiguriert/Online/Offline/Fehler lesen.','Leggere stati Non configurato/Configurato/Online/Offline/Errore.'),
 S('Les clés prestataire restent côté serveur ; ne jamais les saisir dans un champ non prévu.','Provider secrets stay server-side; never enter them into ordinary fields.','Provider-Secrets bleiben serverseitig; nie in normale Felder eingeben.','I segreti provider restano server-side; non inserirli in campi ordinari.')
],{offline:true}),
T('pos-reports','pos','report',['owner','manager'],L('Rapports POS','POS reports','POS-Berichte','Report POS'),L('Lire service, CA, paiements, remboursements, TVA, caisse et food cost.','Read service, revenue, payments, refunds, VAT, cash and food cost.','Service, Umsatz, Zahlungen, Erstattungen, MwSt., Kasse und Food Cost lesen.','Leggere servizio, ricavi, pagamenti, rimborsi, IVA, cassa e food cost.'),[
 S('Sélectionner la date et rafraîchir le rapport une fois les données synchronisées.','Select date and refresh after data is synchronized.','Datum wählen und nach Synchronisation Bericht aktualisieren.','Selezionare data e aggiornare dopo sincronizzazione.'),
 S('Contrôler ventes nettes, moyens de paiement, remboursements, TVA et sessions de caisse.','Review net sales, payment methods, refunds, VAT and cash sessions.','Nettoverkäufe, Zahlungsarten, Erstattungen, MwSt. und Kassensitzungen prüfen.','Controllare vendite nette, pagamenti, rimborsi, IVA e sessioni cassa.'),
 S('Comparer le food cost théorique avec les données du Hub avant conclusion.','Compare theoretical food cost with Hub data before conclusions.','Theoretischen Food Cost vor Schlussfolgerungen mit Hub-Daten vergleichen.','Confrontare food cost teorico con dati Hub prima di concludere.')
]),
T('pos-training','pos','academy',['manager','server','kitchen'],L('Mode entraînement POS','POS training mode','POS-Trainingsmodus','Modalità formazione POS'),L('S’entraîner sur des données fictives sans créer de vente réelle.','Practice on fictitious data without creating real sales.','Mit fiktiven Daten üben, ohne echte Verkäufe zu erzeugen.','Esercitarsi su dati fittizi senza creare vendite reali.'),[
 S('Entrer en entraînement depuis l’Académie : un bandeau indique clairement le mode simulation.','Enter training from Academy; a banner clearly marks simulation mode.','Training über Akademie starten; Banner kennzeichnet Simulation.','Entrare in formazione dall’Academy; un banner indica la simulazione.'),
 S('Simuler ouverture de caisse, table, commande, modificateurs, envoi, paiement et clôture.','Simulate cash opening, table, order, modifiers, send, payment and close.','Kassenöffnung, Tisch, Bestellung, Modifikatoren, Versand, Zahlung und Abschluss simulieren.','Simulare apertura cassa, tavolo, ordine, modificatori, invio, pagamento e chiusura.'),
 S('Aucune action d’entraînement n’appelle les RPC de vente, n’imprime un vrai ticket ou ne modifie la caisse réelle.','Training never calls sales RPCs, prints real receipts or changes real cash.','Training ruft keine Verkaufs-RPCs auf, druckt keine echten Belege und ändert keine echte Kasse.','La formazione non chiama RPC vendita, non stampa scontrini reali e non modifica la cassa reale.')
],{offline:true})
];

export const ACADEMY_PATHS=[
 {id:'first-steps',roles:['owner','manager'],title:L('Premiers pas','First steps','Erste Schritte','Primi passi'),minutes:25,topics:['hub-account-security','hub-organization-users','hub-recipes','hub-stock','hub-haccp','hub-team-planning','hub-pos-admin','hub-pos-layout','pos-first-use','pos-operator','pos-cash-session','pos-ordering','pos-payments','pos-reports']},
 {id:'owner',roles:['owner'],title:L('Parcours propriétaire','Owner path','Inhaber-Pfad','Percorso proprietario'),minutes:35,topics:['hub-dashboard','hub-finance','hub-organization-users','hub-settings-subscription','hub-pos-admin','pos-reports']},
 {id:'manager',roles:['manager'],title:L('Parcours manager','Manager path','Manager-Pfad','Percorso manager'),minutes:45,topics:['hub-dashboard','hub-stock','hub-delivery-ai','hub-suppliers-purchases','hub-haccp','hub-team-planning','hub-recipes','hub-pos-layout','pos-cash-session','pos-reports']},
 {id:'server',roles:['server'],title:L('Serveur / caisse','Server / cashier','Service / Kasse','Sala / cassa'),minutes:20,topics:['pos-operator','pos-floor','pos-ordering','pos-modifiers-menus','pos-payments','pos-split-payments','pos-tickets','pos-offline-sync']},
 {id:'kitchen',roles:['kitchen'],title:L('Cuisine / bar','Kitchen / bar','Küche / Bar','Cucina / bar'),minutes:12,topics:['pos-operator','pos-production','pos-offline-sync']},
 {id:'new-employee',roles:['server','kitchen'],title:L('Nouvel employé — express','New employee — express','Neuer Mitarbeiter — Express','Nuovo dipendente — express'),minutes:12,topics:['pos-operator','pos-ordering','pos-production','pos-payments','pos-offline-sync']}
];

export const ACADEMY_TROUBLESHOOT=[
 {id:'offline',title:L('Je suis hors ligne','I am offline','Ich bin offline','Sono offline'),application:'pos',steps:[
  L('Vérifiez l’indicateur réseau. Si “Hors ligne”, continuez uniquement avec les données déjà synchronisées.','Check network status. If Offline, use only already-synced data.','Netzstatus prüfen. Offline nur synchronisierte Daten nutzen.','Controllare la rete. Offline usare solo dati già sincronizzati.'),
  L('Ouvrez Synchronisation et vérifiez le nombre d’actions en attente.','Open Sync and check pending actions.','Synchronisation öffnen und wartende Aktionen prüfen.','Aprire Sincronizzazione e controllare azioni in attesa.'),
  L('Quand Internet revient, laissez la file se vider avant de répéter une action.','When Internet returns, let the queue drain before repeating actions.','Nach Rückkehr des Internets Warteschlange leeren lassen.','Al ritorno di Internet lasciare svuotare la coda.')
 ]},
 {id:'printer',title:L('Imprimante non détectée','Printer not detected','Drucker nicht erkannt','Stampante non rilevata'),application:'pos',steps:[
  L('Vérifiez alimentation, papier et connexion réseau/Bluetooth selon le profil.','Check power, paper and network/Bluetooth connection.','Strom, Papier und Netzwerk/Bluetooth prüfen.','Controllare alimentazione, carta e rete/Bluetooth.'),
  L('Depuis Imprimantes, relancez la découverte puis testez le profil.','From Printers, rediscover and test the profile.','Unter Drucker erneut suchen und Profil testen.','Da Stampanti, rilanciare ricerca e testare profilo.'),
  L('Si le test échoue, gardez la vente intacte et utilisez une autre imprimante/procédure locale.','If test fails, keep sale intact and use another printer/local procedure.','Bei Fehlschlag Verkauf intakt lassen und Alternativdruck nutzen.','Se fallisce, mantenere vendita e usare altra stampante/procedura.')
 ]},
 {id:'terminal',title:L('Terminal non connecté','Terminal not connected','Terminal nicht verbunden','Terminale non connesso'),application:'pos',steps:[
  L('Vérifiez l’état du profil terminal et le prestataire configuré.','Check terminal profile status and provider.','Terminalprofil und Providerstatus prüfen.','Controllare stato profilo e provider.'),
  L('Pour un terminal externe, ne confirmez le paiement qu’après confirmation réelle sur le terminal.','For external terminal, confirm payment only after real terminal approval.','Externen Zahlungsstatus erst nach echter Terminalbestätigung bestätigen.','Con terminale esterno confermare solo dopo approvazione reale.'),
  L('Si l’état reste Erreur/Hors ligne, basculez sur la procédure de secours du restaurant.','If Error/Offline persists, use the restaurant fallback procedure.','Bei Fehler/Offline Notfallverfahren des Restaurants nutzen.','Se Errore/Offline persiste, usare la procedura di emergenza.')
 ]},
 {id:'sync',title:L('Erreur de synchronisation','Synchronization error','Synchronisationsfehler','Errore sincronizzazione'),application:'common',steps:[
  L('Ne supprimez pas les données locales. Notez le message exact et l’écran concerné.','Do not delete local data. Note the exact message and screen.','Lokale Daten nicht löschen. Exakte Meldung und Bildschirm notieren.','Non eliminare dati locali. Annotare messaggio e schermata.'),
  L('Vérifiez session, restaurant actif et connexion, puis relancez la synchronisation.','Check session, active restaurant and connection, then retry sync.','Sitzung, aktives Restaurant und Verbindung prüfen, dann erneut synchronisieren.','Verificare sessione, ristorante attivo e connessione, poi riprovare.'),
  L('Si le conflit persiste, ne dupliquez pas les opérations et contactez le support avec le contexte technique.','If conflict persists, do not duplicate operations; contact support with technical context.','Bei Konflikt keine Vorgänge duplizieren; Support mit technischem Kontext kontaktieren.','Se persiste, non duplicare operazioni; contattare supporto con contesto tecnico.')
 ]},
 {id:'pin',title:L('PIN oublié','Forgotten PIN','PIN vergessen','PIN dimenticato'),application:'pos',steps:[
  L('Un PIN opérateur ne doit pas être partagé ou deviné par essais répétés.','Operator PINs must not be shared or guessed repeatedly.','Bediener-PIN nicht teilen oder wiederholt erraten.','Non condividere o tentare ripetutamente il PIN.'),
  L('Demandez à un manager autorisé de réinitialiser/configurer le PIN depuis ReMaPro Hub.','Ask an authorized manager to reset/configure PIN from ReMaPro Hub.','Autorisierten Manager um PIN-Reset im Hub bitten.','Chiedere a un manager autorizzato di reimpostare il PIN dal Hub.'),
  L('Reconnectez ensuite l’opérateur sur le POS.','Then sign the operator in again on POS.','Danach Bediener am POS neu anmelden.','Poi riaccedere come operatore sul POS.')
 ]},
 {id:'cash-difference',title:L('Différence de caisse','Cash variance','Kassendifferenz','Differenza di cassa'),application:'pos',steps:[
  L('Recomptez espèces et fond de caisse sans modifier les ventes.','Recount cash and float without changing sales.','Bargeld und Wechselgeld neu zählen, Verkäufe nicht ändern.','Ricontare contanti e fondo senza modificare vendite.'),
  L('Comparez paiements cash, remboursements et mouvements de caisse du rapport de service.','Compare cash payments, refunds and cash movements in service report.','Barzahlungen, Erstattungen und Kassenvorgänge im Servicebericht vergleichen.','Confrontare contanti, rimborsi e movimenti nel report servizio.'),
  L('Documentez l’écart et faites valider par le manager selon la procédure interne.','Document variance and have a manager validate per internal procedure.','Differenz dokumentieren und gemäß Verfahren vom Manager bestätigen lassen.','Documentare la differenza e farla convalidare dal manager.')
 ]}
];

export const ACADEMY_TOURS={
 'hub-dashboard':[
  {selector:'.artisan-top',title:L('Navigation et restaurant','Navigation & restaurant','Navigation & Restaurant','Navigazione e ristorante'),text:L('Vérifiez le restaurant actif, la langue et l’état de synchronisation.','Check active restaurant, language and sync status.','Aktives Restaurant, Sprache und Sync prüfen.','Verificare ristorante, lingua e sincronizzazione.')},
  {selector:'.artisan-kpis',title:L('Indicateurs','KPIs','Kennzahlen','KPI'),text:L('Les indicateurs suivent la période sélectionnée.','KPIs follow the selected period.','Kennzahlen folgen dem gewählten Zeitraum.','I KPI seguono il periodo selezionato.')},
  {selector:'.nav',title:L('Navigation principale','Main navigation','Hauptnavigation','Navigazione principale'),text:L('Utilisez les modules principaux puis “Plus” pour les outils complémentaires.','Use main modules then More for additional tools.','Hauptmodule und Mehr für weitere Werkzeuge nutzen.','Usare moduli principali e Altro per strumenti aggiuntivi.')}
 ],
 'hub-stock':[
  {selector:'#deliveryScanCamera',title:L('Scanner une livraison','Scan delivery','Lieferung scannen','Scansiona consegna'),text:L('Prenez plusieurs photos puis vérifiez chaque résultat avant validation.','Take multiple photos then review each result before validation.','Mehrere Fotos aufnehmen und Ergebnisse vor Bestätigung prüfen.','Scattare più foto e verificare i risultati.')},
  {selector:'#stockForm',title:L('Article stock','Stock item','Lagerartikel','Articolo stock'),text:L('Créez manuellement un article lorsque nécessaire.','Create an item manually when needed.','Bei Bedarf Artikel manuell anlegen.','Creare manualmente un articolo quando necessario.')}
 ],
 'hub-haccp':[{selector:'main',title:L('HACCP','HACCP','HACCP','HACCP'),text:L('Commencez par les contrôles du jour, puis traitez immédiatement les non-conformités.','Start with today’s checks, then handle non-conformities immediately.','Mit heutigen Kontrollen beginnen, Abweichungen sofort bearbeiten.','Iniziare dai controlli di oggi e gestire subito le non conformità.')}],
 'hub-pos-admin':[{selector:'main',title:L('Administration POS','POS administration','POS-Verwaltung','Amministrazione POS'),text:L('Configurez d’abord opérateurs et appareils, puis matériel et implantation.','Configure operators/devices first, then hardware and layout.','Zuerst Bediener/Geräte, dann Hardware/Layout konfigurieren.','Configurare prima operatori/dispositivi, poi hardware/layout.')}],
 'pos-sale':[
  {selector:'.categories',title:L('Catégories','Categories','Kategorien','Categorie'),text:L('Filtrez les produits ou utilisez les favoris.','Filter products or use favorites.','Produkte filtern oder Favoriten nutzen.','Filtrare prodotti o usare preferiti.')},
  {selector:'.products',title:L('Touches produits','Product keys','Produkttasten','Tasti prodotto'),text:L('Touchez un produit puis complétez ses choix éventuels.','Tap a product and complete required choices.','Produkt wählen und Pflichtauswahl abschließen.','Toccare prodotto e completare le scelte.')},
  {selector:'.cart',title:L('Commande','Order','Bestellung','Ordine'),text:L('Vérifiez quantités, notes et total avant envoi ou paiement.','Check quantities, notes and total before send/payment.','Mengen, Notizen und Summe vor Versand/Zahlung prüfen.','Verificare quantità, note e totale prima di invio/pagamento.')},
  {selector:'.payments',title:L('Encaissement','Payment','Zahlung','Pagamento'),text:L('Choisissez le moyen uniquement lorsque le client est prêt à payer.','Choose payment only when customer is ready.','Zahlungsart erst wählen, wenn Kunde bereit ist.','Scegliere il metodo solo quando il cliente è pronto.')}
 ],
 'pos-floor':[{selector:'.table-grid',title:L('Tables','Tables','Tische','Tavoli'),text:L('Une table occupée affiche sa note ouverte ; une table libre peut être ouverte.','Occupied table shows open check; free table can be opened.','Belegter Tisch zeigt offene Rechnung; freier Tisch kann geöffnet werden.','Tavolo occupato mostra conto aperto; tavolo libero può essere aperto.')}],
 'pos-production':[{selector:'.production-grid',title:L('File de production','Production queue','Produktionsliste','Coda produzione'),text:L('Faites progresser le statut seulement quand l’étape est réellement terminée.','Advance status only when the real step is complete.','Status nur bei real abgeschlossenem Schritt ändern.','Avanzare stato solo quando la fase è davvero completata.')}],
 'pos-payment':[{selector:'.payments',title:L('Moyens de paiement','Payment methods','Zahlungsarten','Metodi pagamento'),text:L('Évitez tout double encaissement : vérifiez le résultat terminal avant une seconde tentative.','Avoid double charge: verify terminal result before retry.','Doppelbelastung vermeiden: Terminalergebnis vor erneutem Versuch prüfen.','Evitare doppio addebito: verificare terminale prima di riprovare.')}],
 'pos-sync':[{selector:'.queue-button',title:L('Synchronisation','Synchronization','Synchronisation','Sincronizzazione'),text:L('Le compteur signale les actions encore à envoyer au serveur.','Counter shows actions still pending server sync.','Zähler zeigt noch ausstehende Aktionen.','Il contatore mostra azioni ancora da sincronizzare.')}],
 'hub-account':[{selector:'.artisan-top',title:L('Compte actif','Active account','Aktives Konto','Account attivo'),text:L('Vérifiez votre session, restaurant et langue avant de travailler.','Check session, restaurant and language before work.','Sitzung, Restaurant und Sprache vor der Arbeit prüfen.','Verificare sessione, ristorante e lingua prima di lavorare.')}],
 'hub-organization':[{selector:'main',title:L('Organisation','Organization','Organisation','Organizzazione'),text:L('Gérez restaurants, managers et accès personnel depuis ce module.','Manage restaurants, managers and staff access here.','Restaurants, Manager und Mitarbeiterzugriff hier verwalten.','Gestire ristoranti, manager e accessi personale qui.')}],
 'hub-recipes':[{selector:'main',title:L('Recettes','Recipes','Rezepte','Ricette'),text:L('Créez la recette, reliez le stock et contrôlez le food cost avant publication.','Create recipe, link stock and review food cost before publishing.','Rezept erstellen, Lager verknüpfen und Food Cost vor Veröffentlichung prüfen.','Creare ricetta, collegare stock e verificare food cost prima della pubblicazione.')}],
 'hub-team':[{selector:'main',title:L('Équipe','Team','Team','Team'),text:L('Centralisez employés, planning, absences et formation.','Centralize staff, schedules, leave and training.','Mitarbeiter, Planung, Abwesenheiten und Training zentral verwalten.','Centralizzare personale, turni, assenze e formazione.')}],
 'hub-finance':[{selector:'main',title:L('Pilotage financier','Financial management','Finanzsteuerung','Controllo finanziario'),text:L('Commencez par la période, puis lisez CA, dépenses et moyens de paiement.','Start with period, then read revenue, expenses and payment methods.','Mit Zeitraum beginnen, dann Umsatz, Ausgaben und Zahlungsarten lesen.','Partire dal periodo, poi leggere ricavi, spese e pagamenti.')}],
 'hub-pos-layout':[{selector:'main',title:L('Implantation caisse','POS layout','Kassenlayout','Layout cassa'),text:L('Prévisualisez toujours avant de publier une nouvelle version aux tablettes.','Always preview before publishing a new version to tablets.','Vor Veröffentlichung auf Tablets immer Vorschau prüfen.','Fare sempre anteprima prima di pubblicare sui tablet.')}],
 'pos-setup':[{selector:'.topbar',title:L('État POS','POS status','POS-Status','Stato POS'),text:L('Vérifiez restaurant, opérateur, synchronisation et réseau avant le service.','Check restaurant, operator, sync and network before service.','Restaurant, Bediener, Sync und Netzwerk vor Service prüfen.','Verificare ristorante, operatore, sync e rete prima del servizio.')}],
 'pos-cash':[{selector:'.session-chip',title:L('Session de caisse','Cash session','Kassensitzung','Sessione cassa'),text:L('Ce badge confirme la session ouverte et son fond de caisse.','This badge confirms the open session and its cash float.','Dieses Badge zeigt offene Sitzung und Wechselgeld.','Questo badge conferma sessione aperta e fondo cassa.')}]
};

export const ACADEMY_COVERAGE={
 hub:{
  'account.create':'hub-account-security','account.signin':'hub-account-security','account.signout':'hub-account-security','account.biometric':'hub-account-security','account.security':'hub-account-security',
  'organization.organizations':'hub-organization-users','organization.restaurants':'hub-organization-users','organization.users':'hub-organization-users','organization.roles':'hub-organization-users','organization.permissions':'hub-organization-users','organization.add_remove_user':'hub-organization-users',
  'dashboard.cockpit':'hub-dashboard','dashboard.kpis':'hub-dashboard','dashboard.alerts':'hub-dashboard','dashboard.tasks':'hub-dashboard','dashboard.filters':'hub-dashboard','dashboard.quick_actions':'hub-dashboard',
  'recipes.create':'hub-recipes','recipes.ingredients':'hub-recipes','recipes.quantities':'hub-recipes','recipes.units':'hub-recipes','recipes.costs':'hub-recipes','recipes.margin':'hub-recipes','recipes.suggested_price':'hub-recipes','recipes.subrecipes':'hub-recipes','recipes.price_impact':'hub-recipes','recipes.publish_pos':'hub-recipes',
  'stock.items':'hub-stock','stock.categories':'hub-stock','stock.levels':'hub-stock','stock.thresholds':'hub-stock','stock.inventory':'hub-stock','stock.waste':'hub-stock','stock.corrections':'hub-stock','stock.movements':'hub-stock','stock.valuation':'hub-stock','stock.theoretical_actual':'hub-stock',
  'stock.ai_photos':'hub-delivery-ai','stock.ai_ocr':'hub-delivery-ai','stock.ai_barcode':'hub-delivery-ai','stock.ai_matching':'hub-delivery-ai','stock.ai_validation':'hub-delivery-ai',
  'suppliers.suppliers':'hub-suppliers-purchases','suppliers.products':'hub-suppliers-purchases','suppliers.prices':'hub-suppliers-purchases','purchases.orders':'hub-suppliers-purchases','purchases.deliveries':'hub-suppliers-purchases','purchases.variances':'hub-suppliers-purchases','purchases.history':'hub-suppliers-purchases','purchases.reorder':'hub-suppliers-purchases',
  'haccp.records':'hub-haccp','haccp.temperature':'hub-haccp','haccp.cleaning':'hub-haccp','haccp.receiving':'hub-haccp','haccp.nonconformity':'hub-haccp','haccp.corrective':'hub-haccp','haccp.history':'hub-haccp','haccp.export_inspection':'hub-haccp',
  'team.employees':'hub-team-planning','team.roles':'hub-team-planning','team.planning':'hub-team-planning','team.leave':'hub-team-planning','team.hours':'hub-team-planning','team.labor_cost':'hub-team-planning','team.access':'hub-organization-users',
  'hr.contract':'hub-hr-documents','hr.extra':'hub-hr-documents','hr.payslip':'hub-hr-documents','hr.documents':'hub-hr-documents',
  'finance.revenue':'hub-finance','finance.expenses':'hub-finance','finance.payment_methods':'hub-finance','finance.reports':'hub-finance','finance.comparisons':'hub-finance','finance.exports':'hub-finance','finance.indicators':'hub-finance',
  'ai.ask':'hub-ai','ai.context':'hub-ai','ai.limits':'hub-ai','ai.validation':'hub-ai','ai.use_cases':'hub-ai',
  'posadmin.activate':'hub-pos-admin','posadmin.settings':'hub-pos-admin','posadmin.devices':'hub-pos-admin','posadmin.operators':'hub-pos-admin','posadmin.pin':'hub-pos-admin','posadmin.permissions':'hub-pos-admin','posadmin.terminals':'hub-pos-admin','posadmin.printers':'hub-pos-admin','posadmin.stations':'hub-pos-admin','posadmin.sync':'hub-pos-admin','posadmin.reports':'hub-pos-admin',
  'layout.pages':'hub-pos-layout','layout.categories':'hub-pos-layout','layout.keys':'hub-pos-layout','layout.color':'hub-pos-layout','layout.size':'hub-pos-layout','layout.order':'hub-pos-layout','layout.subpages':'hub-pos-layout','layout.favorites':'hub-pos-layout','layout.hidden':'hub-pos-layout','layout.modifiers':'hub-pos-layout','layout.menus':'hub-pos-layout','layout.preview':'hub-pos-layout','layout.publish':'hub-pos-layout','layout.rollback':'hub-pos-layout',
  'customers.reservations':'hub-reservations-customers','customers.records':'hub-reservations-customers','customers.loyalty':'hub-reservations-customers',
  'operations.checklists':'hub-compliance-ops','operations.incidents':'hub-compliance-ops','operations.maintenance':'hub-compliance-ops','operations.equipment':'hub-compliance-ops','operations.audits':'hub-compliance-ops','operations.recalls':'hub-compliance-ops','operations.allergens':'hub-compliance-ops',
  'settings.language':'hub-settings-subscription','settings.appearance':'hub-settings-subscription','settings.notifications':'hub-settings-subscription','settings.backup':'hub-settings-subscription','settings.subscription':'hub-settings-subscription'
 },
 pos:{
  'setup.install':'pos-first-use','setup.login':'pos-first-use','setup.restaurant':'pos-first-use','setup.device':'pos-first-use','setup.initial_sync':'pos-first-use',
  'operator.pin':'pos-operator','operator.switch':'pos-operator','operator.permissions':'pos-operator','operator.manager_actions':'pos-operator',
  'cash.open':'pos-cash-session','cash.float':'pos-cash-session','cash.status':'pos-cash-session','cash.close':'pos-cash-session','cash.count':'pos-cash-session','cash.variance':'pos-cash-session',
  'floor.tables':'pos-floor','floor.covers':'pos-floor','floor.open_table':'pos-floor','floor.transfer':'pos-floor','floor.merge_split':'pos-floor','floor.open_checks':'pos-floor',
  'order.categories':'pos-ordering','order.product_keys':'pos-ordering','order.quantity':'pos-ordering','order.delete':'pos-ordering','order.after_send':'pos-ordering','order.open_item':'pos-ordering','order.notes':'pos-ordering',
  'order.modifiers':'pos-modifiers-menus','order.cooking':'pos-modifiers-menus','order.sides':'pos-modifiers-menus','order.extras':'pos-modifiers-menus','order.menus':'pos-modifiers-menus',
  'production.send':'pos-production','production.tickets':'pos-production','production.status':'pos-production','production.preparing':'pos-production','production.ready':'pos-production','production.served':'pos-production','production.reprint':'pos-production','production.routing':'pos-production',
  'payment.cash':'pos-payments','payment.card':'pos-payments','payment.twint':'pos-payments','payment.external':'pos-payments','payment.tip':'pos-payments','payment.cancel':'pos-payments','payment.pending':'pos-payments','payment.failed':'pos-payments',
  'payment.split_amount':'pos-split-payments','payment.split_items':'pos-split-payments','payment.progressive':'pos-split-payments',
  'ticket.master':'pos-tickets','ticket.split':'pos-tickets','ticket.reprint':'pos-tickets','ticket.number':'pos-tickets','ticket.history':'pos-tickets',
  'refund.full':'pos-refunds','refund.partial':'pos-refunds','refund.external':'pos-refunds','refund.audit':'pos-refunds',
  'offline.available':'pos-offline-sync','offline.queue':'pos-offline-sync','offline.reconnect':'pos-offline-sync','offline.conflicts':'pos-offline-sync','offline.local_data':'pos-offline-sync','offline.best_practices':'pos-offline-sync',
  'hardware.printers':'pos-printers','hardware.discovery':'pos-printers','hardware.test':'pos-printers','hardware.profile':'pos-printers','hardware.routing':'pos-printers','hardware.cash_drawer':'pos-printers',
  'hardware.terminals':'pos-terminals','hardware.connection_state':'pos-terminals','hardware.compatibility':'pos-terminals',
  'reports.service':'pos-reports','reports.revenue':'pos-reports','reports.payments':'pos-reports','reports.refunds':'pos-reports','reports.vat':'pos-reports','reports.cash_float':'pos-reports','reports.food_cost':'pos-reports',
  'training.safe_mode':'pos-training','training.fake_data':'pos-training','training.order':'pos-training','training.payment':'pos-training','training.close':'pos-training'
 }
};
