import{LANGS,language,setLanguage,t}from'./i18n.js';
const modules=['operations','haccp','finance','documents','stock','suppliers','team','settings'];
let page='dashboard';
const state={revenue:0,covers:0,expenses:0,stock:[],temps:[],tasks:[['openKitchen',false],['temperatureCheck',false],['diningSetup',false],['cashCheck',false],['closingCleaning',false]],docs:['traceability','nonConformity','recipeSheet','purchaseOrder','inspectionPrep','inventory'],suppliers:[],team:[]};
const money=n=>new Intl.NumberFormat(language(),{style:'currency',currency:'CHF'}).format(n||0);
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
function dashboard(){const avg=state.covers?state.revenue/state.covers:0;return `<section><h1>${t('dashboard')}</h1><p class="muted">${t('dashboardSub')}</p><div class="grid">${card(t('revenue'),`<div class="kpi">${money(state.revenue)}</div><div class="muted">${state.revenue?t('today'):t('noSales')}</div>`)}${card(t('covers'),`<div class="kpi">${state.covers}</div>`)}${card(t('avg'),`<div class="kpi">${money(avg)}</div>`)}${card(t('expenses'),`<div class="kpi">${money(state.expenses)}</div>`)}</div><div class="modules">${modules.map(k=>`<button class="module" data-page="${k}"><strong>${t(k)}</strong></button>`).join('')}</div></section>`}
function operations(){return `<section><h1>${t('operations')}</h1><p class="muted">${t('operationsSub')}</p>${card(t('todayTasks'),state.tasks.map((x,i)=>`<label class="row"><span>${t(x[0])}</span><input type="checkbox" data-task="${i}" ${x[1]?'checked':''}></label>`).join(''))}</section>`}
function haccp(){return `<section><h1>${t('haccp')}</h1><p class="muted">${t('haccpSub')}</p>${card(t('temperatureReadings'),`<form id="tempForm" class="form"><input name="equipment" required placeholder="${t('equipment')}"><input name="value" required type="number" step="0.1" placeholder="°C"><button class="btn primary">${t('add')}</button></form>${state.temps.length?state.temps.map(x=>`<div class="row"><span>${x.equipment}</span><strong>${x.value} °C</strong></div>`).join(''):`<p class="muted">${t('noReadings')}</p>`}`)}</section>`}
function finance(){return `<section><h1>${t('finance')}</h1><p class="muted">${t('financeSub')}</p><div class="grid">${card(t('revenue'),`<div class="kpi">${money(state.revenue)}</div>`)}${card(t('expenses'),`<div class="kpi">${money(state.expenses)}</div>`)}${card(t('result'),`<div class="kpi">${money(state.revenue-state.expenses)}</div>`)}</div>${card(t('dailyEntry'),`<form id="financeForm" class="form"><input name="revenue" type="number" step="0.01" placeholder="${t('revenue')}"><input name="covers" type="number" placeholder="${t('covers')}"><input name="expenses" type="number" step="0.01" placeholder="${t('expenses')}"><button class="btn primary">${t('save')}</button></form>`)}</section>`}
function documents(){return `<section><h1>${t('documents')}</h1><p class="muted">${t('documentsSub')}</p><div class="modules">${state.docs.map(k=>`<article class="card"><strong>${t(k)}</strong><div class="actions"><button class="btn">${t('fill')}</button><button class="btn">${t('download')}</button></div></article>`).join('')}</div></section>`}
function stock(){return `<section><h1>${t('stock')}</h1>${card(t('inventory'),`<form id="stockForm" class="form"><input name="name" required placeholder="${t('product')}"><input name="qty" required type="number" step="0.01" placeholder="${t('quantity')}"><input name="price" type="number" step="0.01" placeholder="${t('purchasePrice')}"><button class="btn primary">${t('add')}</button></form>${state.stock.map(x=>`<div class="row"><span>${x.name}</span><strong>${x.qty} · ${money(x.price)}</strong></div>`).join('')}`)}</section>`}
function simple(key,desc){return `<section><h1>${t(key)}</h1><p class="muted">${t(desc)}</p>${card(t('comingCore'),`<p>${t('moduleReady')}</p>`)}</section>`}
function view(){if(page==='dashboard')return dashboard();if(page==='operations')return operations();if(page==='haccp')return haccp();if(page==='finance')return finance();if(page==='documents')return documents();if(page==='stock')return stock();if(page==='suppliers')return simple('suppliers','suppliersSub');if(page==='team')return simple('team','teamSub');if(page==='settings')return simple('settings','settingsSub');return dashboard()}
function render(){const l=language();document.documentElement.lang=l;document.getElementById('app').innerHTML=`<main class="shell"><header class="top"><div><div class="brand">ReMaPro Hub</div><div class="muted">${t('account')}</div></div><select id="lang" class="lang">${LANGS.map(x=>`<option value="${x}" ${x===l?'selected':''}>${x.toUpperCase()}</option>`).join('')}</select></header>${view()}</main><nav class="nav"><button data-page="dashboard">${t('dashboard')}</button><button data-page="operations">${t('operations')}</button><button data-page="finance">${t('finance')}</button><button data-page="documents">${t('documents')}</button></nav>`;bind()}
function bind(){document.getElementById('lang')?.addEventListener('change',e=>setLanguage(e.target.value));document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render()}));document.querySelectorAll('[data-task]').forEach(x=>x.addEventListener('change',()=>{state.tasks[+x.dataset.task][1]=x.checked}));document.getElementById('financeForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.revenue=+f.get('revenue')||0;state.covers=+f.get('covers')||0;state.expenses=+f.get('expenses')||0;render()});document.getElementById('tempForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.temps.unshift({equipment:f.get('equipment'),value:f.get('value')});render()});document.getElementById('stockForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.stock.unshift({name:f.get('name'),qty:+f.get('qty'),price:+f.get('price')||0});render()})}
window.addEventListener('rmp:language',render);render();
