const KEY='remaprohub.v27.state';
const defaults={revenue:0,covers:0,expenses:0,sales:[],orders:[],products:[],loyalty:[],briefings:[],invoices:[],checklists:[],alerts:[],goals:[],training:[],leave:[],equipment:[],audits:[],cleaning:[],deliveries:[],allergens:[],recalls:[],financeHistory:[],stock:[],temps:[],suppliers:[],purchases:[],team:[],shifts:[],incidents:[],waste:[],reservations:[],customers:[],recipes:[],maintenance:[],handover:[],categories:[],tasksDate:'',tasks:[['openKitchen',false],['temperatureCheck',false],['diningSetup',false],['cashCheck',false],['closingCleaning',false]],docs:['traceability','nonConformity','recipeSheet','purchaseOrder','inspectionPrep','inventory'],documentEntries:[],preferences:{restaurant:'',currency:'CHF',theme:'taupe'}};
function clone(v){return JSON.parse(JSON.stringify(v))}function migrateFinance(rows){return(rows||[]).map(x=>{const r={...x};if(r.manualRevenue==null)r.manualRevenue=+r.revenue||0;if(r.orderRevenue==null)r.orderRevenue=0;if(r.manualExpenses==null)r.manualExpenses=+r.expenses||0;if(r.purchaseExpenses==null)r.purchaseExpenses=0;r.revenue=(+r.manualRevenue||0)+(+r.orderRevenue||0);r.expenses=(+r.manualExpenses||0)+(+r.purchaseExpenses||0);return r})}function merge(base,raw){const out=Object.assign(clone(base),raw||{});out.preferences=Object.assign({},base.preferences,raw?.preferences||{});for(const k of Object.keys(base))if(Array.isArray(base[k])&&!Array.isArray(out[k]))out[k]=clone(base[k]);out.stock=out.stock.map((x,i)=>({...x,id:x.id||`legacy-stock-${i}`}));out.financeHistory=migrateFinance(out.financeHistory);return out}
export function newStockId(){return globalThis.crypto?.randomUUID?.()||`stock-${Date.now()}-${Math.random().toString(36).slice(2)}`}
export function stockAvailable(state,item){const received=(state.deliveries||[]).reduce((sum,delivery)=>sum+(item.id&&delivery.status==='accepted'&&delivery.stockId===item.id?(+delivery.qty||0):0),0);const lost=(state.waste||[]).reduce((sum,waste)=>sum+(item.id&&waste.stockId===item.id?(+waste.qty||0):0),0);return(+item.qty||0)+received-lost}
export function wasteCapacity(state,stockId,index=-1){const item=state.stock?.find(x=>x.id===stockId);if(!item)return null;const previous=state.waste?.[index];return stockAvailable(state,item)+(previous?.stockId===stockId?(+previous.qty||0):0)}
export function recordWaste(state,{stockId,qty}){const item=state.stock?.find(x=>x.id===stockId),amount=+qty,available=wasteCapacity(state,stockId);if(!item||!Number.isFinite(amount)||amount<=0||amount>available+1e-9)return false;state.waste.unshift({stockId,product:item.name,qty:amount});return true}
export function updateWaste(state,index,{stockId,qty}){if(!Number.isInteger(index)||index<0||!state.waste?.[index])return false;const item=state.stock?.find(x=>x.id===stockId),amount=+qty,available=wasteCapacity(state,stockId,index);if(!item||!Number.isFinite(amount)||amount<=0||amount>available+1e-9)return false;state.waste[index]={...state.waste[index],stockId,product:item.name,qty:amount};return true}
export function localDate(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
export function ensureDailyTasks(state,now=new Date()){const day=localDate(now);if(state.tasksDate===day)return false;state.tasks=(state.tasks||[]).map(([key])=>[key,false]);state.tasksDate=day;return true}
export function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(defaults)}}export function save(state){localStorage.setItem(KEY,JSON.stringify(state));return state}export function reset(){localStorage.removeItem(KEY);return clone(defaults)}export function resetState(state){const fresh=clone(defaults);for(const key of Object.keys(state))delete state[key];Object.assign(state,fresh);save(state);return state}export function exportData(state){return JSON.stringify({version:27,exportedAt:new Date().toISOString(),state},null,2)}
export function importData(state,text){let backup;try{backup=JSON.parse(text)}catch{return false}if(backup?.version!==27||!backup.state||typeof backup.state!=='object'||Array.isArray(backup.state))return false;const raw=backup.state;for(const [key,value] of Object.entries(defaults)){if(Array.isArray(value)){if(!Array.isArray(raw[key]))return false;if(key==='docs'){if(!raw[key].every(x=>typeof x==='string'))return false}else if(key==='tasks'){if(!raw[key].every(x=>Array.isArray(x)&&typeof x[0]==='string'&&typeof x[1]==='boolean'))return false}else if(!raw[key].every(x=>x&&typeof x==='object'&&!Array.isArray(x)))return false}}if(!raw.preferences||typeof raw.preferences!=='object'||Array.isArray(raw.preferences))return false;if(!raw.financeHistory.every(x=>typeof x.date==='string'))return false;const clean={};for(const key of Object.keys(defaults))clean[key]=raw[key]??clone(defaults[key]);const next=merge(defaults,clean);if(!['CHF','EUR','USD','GBP'].includes(next.preferences.currency)||!['taupe','light','dark'].includes(next.preferences.theme))return false;save(next);for(const key of Object.keys(state))delete state[key];Object.assign(state,next);return true}
export function updatePreferences(state,patch){if(!state||!patch||typeof patch!=='object')return false;state.preferences=Object.assign({},defaults.preferences,state.preferences||{},patch);if(typeof state.preferences.restaurant!=='string')state.preferences.restaurant='';if(!['CHF','EUR','USD','GBP'].includes(state.preferences.currency))state.preferences.currency='CHF';save(state);return true}
function documentFields(fields){const result={};if(fields&&typeof fields==='object'&&!Array.isArray(fields))for(const [key,value] of Object.entries(fields))if(/^[a-zA-Z]+$/.test(key)&&typeof value==='string')result[key]=value;return result}
export function saveDocument(state,{type,date,title,details,fields}){if(!state||!Array.isArray(state.documentEntries))return false;state.documentEntries.unshift({type:String(type||''),date:String(date||localDate()),title:String(title||''),details:String(details||''),fields:documentFields(fields),createdAt:new Date().toISOString()});save(state);return true}
export function updateDocument(state,index,{type,date,title,details,fields}){const old=state?.documentEntries?.[index];if(!old||!Number.isInteger(index)||index<0)return false;state.documentEntries[index]={...old,type:String(type||old.type),date:String(date||old.date),title:String(title||''),details:String(details||''),fields:fields===undefined?documentFields(old.fields):documentFields(fields)};save(state);return true}
function deliveryContribution(row,id){return row?.stockId===id&&row.status==='accepted'?(+row.qty||0):0}
function deliveryChangeAllowed(state,old,next){for(const id of new Set([old.stockId,next?.stockId])){const item=state.stock?.find(x=>x.id===id);if(!item)continue;const current=stockAvailable(state,item),after=current-deliveryContribution(old,id)+deliveryContribution(next,id);if(after< -1e-9&&after<current-1e-9)return false}return true}
export function updateRecord(state,collection,index,record){const list=state?.[collection];if(!Array.isArray(list)||!Number.isInteger(index)||index<0||index>=list.length||!record||typeof record!=='object')return false;const next={...list[index],...record};if(collection==='deliveries'&&(!Number.isFinite(+next.qty)||+next.qty<=0||!deliveryChangeAllowed(state,list[index],next)))return false;if(collection==='stock'&&(!Number.isFinite(+next.qty)||+next.qty<0))return false;if(collection==='stock'&&(+next.qty||0)<(+list[index].qty||0)-1e-9&&stockAvailable(state,list[index])+(+next.qty||0)-(+list[index].qty||0)< -1e-9)return false;list[index]=next;return true}
export function removeRecord(state,collection,index){if(collection==='financeHistory')return clearFinanceDay(state,index);const list=state?.[collection];if(!Array.isArray(list)||!Number.isInteger(index)||index<0||index>=list.length)return false;if(collection==='deliveries'&&!deliveryChangeAllowed(state,list[index],null))return false;list.splice(index,1);return true}
export function clearFinanceDay(state,index){const day=state?.financeHistory?.[index];if(!day||!Number.isInteger(index)||index<0)return false;day.manualRevenue=0;day.manualExpenses=0;day.covers=0;day.revenue=+day.orderRevenue||0;day.expenses=+day.purchaseExpenses||0;if(!day.revenue&&!day.expenses)state.financeHistory.splice(index,1);syncFinanceSnapshot(state);return true}
function ensureFinanceDay(state,date){const day=date||localDate();let x=state.financeHistory.find(v=>v.date===day);if(!x){x={date:day,manualRevenue:0,orderRevenue:0,covers:0,manualExpenses:0,purchaseExpenses:0,revenue:0,expenses:0};state.financeHistory.push(x)}if(x.manualRevenue==null)x.manualRevenue=+x.revenue||0;if(x.orderRevenue==null)x.orderRevenue=0;if(x.manualExpenses==null)x.manualExpenses=+x.expenses||0;if(x.purchaseExpenses==null)x.purchaseExpenses=0;x.revenue=(+x.manualRevenue||0)+(+x.orderRevenue||0);x.expenses=(+x.manualExpenses||0)+(+x.purchaseExpenses||0);return x}
function financeDelta(state,date,revenueDelta=0,expenseDelta=0){const x=ensureFinanceDay(state,date);x.orderRevenue=(+x.orderRevenue||0)+revenueDelta;x.purchaseExpenses=(+x.purchaseExpenses||0)+expenseDelta;x.revenue=(+x.manualRevenue||0)+(+x.orderRevenue||0);x.expenses=(+x.manualExpenses||0)+(+x.purchaseExpenses||0);state.financeHistory.sort((a,b)=>b.date.localeCompare(a.date));syncFinanceSnapshot(state);return x}
export function recordOrder(state,{reference,amount,status='open',date}){const entry={reference:String(reference||''),amount:+amount||0,status:String(status||'open'),date:date||localDate()};state.orders.unshift(entry);if(entry.status==='paid')financeDelta(state,entry.date,entry.amount,0);return entry}
export function updateOrder(state,index,patch){const old=state?.orders?.[index];if(!old)return false;if(old.status==='paid')financeDelta(state,old.date,-(+old.amount||0),0);state.orders[index]={...old,...patch,amount:+patch.amount||0};const next=state.orders[index];if(next.status==='paid')financeDelta(state,next.date,+next.amount||0,0);return true}
export function removeOrder(state,index){const old=state?.orders?.[index];if(!old)return false;if(old.status==='paid')financeDelta(state,old.date,-(+old.amount||0),0);state.orders.splice(index,1);return true}
export function recordPurchase(state,{supplier,date,amount,note}){const entry={supplier:String(supplier||''),date:date||localDate(),amount:+amount||0,note:String(note||'')};state.purchases.unshift(entry);financeDelta(state,entry.date,0,entry.amount);return entry}
export function updatePurchase(state,index,patch){const old=state?.purchases?.[index];if(!old)return false;financeDelta(state,old.date,0,-(+old.amount||0));state.purchases[index]={...old,...patch,amount:+patch.amount||0};const next=state.purchases[index];financeDelta(state,next.date,0,+next.amount||0);return true}
export function removePurchase(state,index){const old=state?.purchases?.[index];if(!old)return false;financeDelta(state,old.date,0,-(+old.amount||0));state.purchases.splice(index,1);return true}
export function syncFinanceSnapshot(state){const latest=state.financeHistory?.[0]||{revenue:0,covers:0,expenses:0};state.revenue=+latest.revenue||0;state.covers=+latest.covers||0;state.expenses=+latest.expenses||0;return latest}
export function recordFinance(state,{date,revenue,covers,expenses}){const x=ensureFinanceDay(state,date);x.manualRevenue=+revenue||0;x.manualExpenses=+expenses||0;x.covers=+covers||0;x.revenue=x.manualRevenue+(+x.orderRevenue||0);x.expenses=x.manualExpenses+(+x.purchaseExpenses||0);state.financeHistory.sort((a,b)=>b.date.localeCompare(a.date));syncFinanceSnapshot(state);return x}
export function financeTotals(state,period='day',now=new Date()){const start=new Date(now);start.setHours(0,0,0,0);if(period==='month')start.setDate(1);else if(period==='week')start.setDate(start.getDate()-(start.getDay()+6)%7);const rows=state.financeHistory.filter(x=>{const d=new Date(`${x.date}T00:00:00`);return d>=start&&d<=now});return rows.reduce((a,x)=>(a.revenue+=+x.revenue||0,a.covers+=+x.covers||0,a.expenses+=+x.expenses||0,a),{revenue:0,covers:0,expenses:0,rows})}
export function financeDayTotals(state,date=localDate()){const selected=/^\d{4}-\d{2}-\d{2}$/.test(date||'')?date:localDate();return financeTotals(state,'day',new Date(`${selected}T23:59:59.999`))}
export function revenueSeries(state,period='day',now=new Date()){const count=period==='month'?6:7,anchor=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(period==='week')anchor.setDate(anchor.getDate()-(anchor.getDay()+6)%7);if(period==='month')anchor.setDate(1);const points=Array.from({length:count},(_,index)=>{const date=new Date(anchor);if(period==='month')date.setMonth(date.getMonth()-(count-1-index));else date.setDate(date.getDate()-(count-1-index)*(period==='week'?7:1));return{key:localDate(date),date,revenue:0}}),byKey=new Map(points.map(point=>[point.key,point]));for(const row of state.financeHistory||[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(row.date||''))continue;const date=new Date(`${row.date}T12:00:00`);if(Number.isNaN(date.getTime())||localDate(date)!==row.date||row.date>localDate(now))continue;if(period==='week')date.setDate(date.getDate()-(date.getDay()+6)%7);if(period==='month')date.setDate(1);const point=byKey.get(localDate(date));if(point)point.revenue+=+row.revenue||0}return points}
