const KEY='remaprohub.v27.state';
const defaults={revenue:0,covers:0,expenses:0,sales:[],orders:[],products:[],loyalty:[],briefings:[],invoices:[],checklists:[],alerts:[],financeHistory:[],stock:[],temps:[],suppliers:[],purchases:[],team:[],shifts:[],incidents:[],waste:[],reservations:[],customers:[],recipes:[],maintenance:[],handover:[],categories:[],tasks:[['openKitchen',false],['temperatureCheck',false],['diningSetup',false],['cashCheck',false],['closingCleaning',false]],docs:['traceability','nonConformity','recipeSheet','purchaseOrder','inspectionPrep','inventory'],documentEntries:[],preferences:{restaurant:'',currency:'CHF',theme:'taupe'}};
function clone(v){return JSON.parse(JSON.stringify(v))}function merge(base,raw){const out=Object.assign(clone(base),raw||{});out.preferences=Object.assign({},base.preferences,raw?.preferences||{});for(const k of Object.keys(base))if(Array.isArray(base[k])&&!Array.isArray(out[k]))out[k]=clone(base[k]);return out}
export function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(defaults)}}export function save(state){localStorage.setItem(KEY,JSON.stringify(state));return state}export function reset(){localStorage.removeItem(KEY);return clone(defaults)}export function resetState(state){const fresh=clone(defaults);for(const key of Object.keys(state))delete state[key];Object.assign(state,fresh);save(state);return state}export function exportData(state){return JSON.stringify({version:27,exportedAt:new Date().toISOString(),state},null,2)}
export function updatePreferences(state,patch){if(!state||!patch||typeof patch!=='object')return false;state.preferences=Object.assign({},defaults.preferences,state.preferences||{},patch);if(typeof state.preferences.restaurant!=='string')state.preferences.restaurant='';if(!['CHF','EUR','USD','GBP'].includes(state.preferences.currency))state.preferences.currency='CHF';save(state);return true}
export function saveDocument(state,{type,date,title,details}){if(!state||!Array.isArray(state.documentEntries))return false;state.documentEntries.unshift({type:String(type||''),date:String(date||new Date().toISOString().slice(0,10)),title:String(title||''),details:String(details||''),createdAt:new Date().toISOString()});save(state);return true}
export function updateRecord(state,collection,index,record){const list=state?.[collection];if(!Array.isArray(list)||!Number.isInteger(index)||index<0||index>=list.length||!record||typeof record!=='object')return false;list[index]={...list[index],...record};return true}
export function removeRecord(state,collection,index){const list=state?.[collection];if(!Array.isArray(list)||!Number.isInteger(index)||index<0||index>=list.length)return false;list.splice(index,1);if(collection==='financeHistory')syncFinanceSnapshot(state);return true}
function financeDelta(state,date,revenueDelta=0,expenseDelta=0){const day=date||new Date().toISOString().slice(0,10),x=state.financeHistory.find(v=>v.date===day)||{date:day,revenue:0,covers:0,expenses:0};return recordFinance(state,{date:day,revenue:(+x.revenue||0)+revenueDelta,covers:+x.covers||0,expenses:(+x.expenses||0)+expenseDelta})}
export function recordOrder(state,{reference,amount,status='open',date}){const entry={reference:String(reference||''),amount:+amount||0,status:String(status||'open'),date:date||new Date().toISOString().slice(0,10)};state.orders.unshift(entry);if(entry.status==='paid')financeDelta(state,entry.date,entry.amount,0);return entry}
export function updateOrder(state,index,patch){const old=state?.orders?.[index];if(!old)return false;if(old.status==='paid')financeDelta(state,old.date,-(+old.amount||0),0);state.orders[index]={...old,...patch,amount:+patch.amount||0};const next=state.orders[index];if(next.status==='paid')financeDelta(state,next.date,+next.amount||0,0);return true}
export function removeOrder(state,index){const old=state?.orders?.[index];if(!old)return false;if(old.status==='paid')financeDelta(state,old.date,-(+old.amount||0),0);state.orders.splice(index,1);return true}
export function recordPurchase(state,{supplier,date,amount,note}){const entry={supplier:String(supplier||''),date:date||new Date().toISOString().slice(0,10),amount:+amount||0,note:String(note||'')};state.purchases.unshift(entry);financeDelta(state,entry.date,0,entry.amount);return entry}
export function updatePurchase(state,index,patch){const old=state?.purchases?.[index];if(!old)return false;financeDelta(state,old.date,0,-(+old.amount||0));state.purchases[index]={...old,...patch,amount:+patch.amount||0};const next=state.purchases[index];financeDelta(state,next.date,0,+next.amount||0);return true}
export function removePurchase(state,index){const old=state?.purchases?.[index];if(!old)return false;financeDelta(state,old.date,0,-(+old.amount||0));state.purchases.splice(index,1);return true}
export function syncFinanceSnapshot(state){const latest=state.financeHistory?.[0]||{revenue:0,covers:0,expenses:0};state.revenue=+latest.revenue||0;state.covers=+latest.covers||0;state.expenses=+latest.expenses||0;return latest}
export function recordFinance(state,{date,revenue,covers,expenses}){const day=date||new Date().toISOString().slice(0,10),entry={date:day,revenue:+revenue||0,covers:+covers||0,expenses:+expenses||0},i=state.financeHistory.findIndex(x=>x.date===day);if(i>=0)state.financeHistory[i]=entry;else state.financeHistory.unshift(entry);state.financeHistory.sort((a,b)=>b.date.localeCompare(a.date));state.revenue=entry.revenue;state.covers=entry.covers;state.expenses=entry.expenses;return entry}
export function financeTotals(state,period='day',now=new Date()){const days=period==='month'?31:period==='week'?7:1,start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-days+1);const rows=state.financeHistory.filter(x=>{const d=new Date(`${x.date}T00:00:00`);return d>=start&&d<=now});if(!rows.length&&period==='day')return{revenue:+state.revenue||0,covers:+state.covers||0,expenses:+state.expenses||0,rows:[]};return rows.reduce((a,x)=>(a.revenue+=+x.revenue||0,a.covers+=+x.covers||0,a.expenses+=+x.expenses||0,a),{revenue:0,covers:0,expenses:0,rows})}
