-- ReMaPro POS v0.19: immutable line food-cost snapshots and idempotent stock-consumption ledger.
alter table public.pos_order_items
  add column if not exists unit_cost_snapshot numeric(14,4) not null default 0,
  add column if not exists cost_total numeric(14,2) not null default 0;

create table if not exists public.pos_inventory_movements (
  id uuid primary key default gen_random_uuid(),
  sequence bigint generated by default as identity unique,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  order_id uuid not null references public.pos_orders(id) on delete restrict,
  order_item_id uuid not null references public.pos_order_items(id) on delete restrict,
  catalog_item_id uuid references public.pos_catalog_items(id) on delete set null,
  hub_stock_id text,
  stock_source_key text not null,
  stock_name text not null,
  unit text not null default 'unit',
  kind text not null default 'sale' check (kind in ('sale','manual_reversal')),
  quantity_delta numeric(14,4) not null,
  unit_cost numeric(14,4) not null default 0,
  total_cost numeric(14,2) not null default 0,
  business_date date not null,
  receipt_number text,
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(order_item_id,stock_source_key,kind)
);
create index if not exists pos_inventory_movements_restaurant_seq_idx on public.pos_inventory_movements(restaurant_id,sequence);
create index if not exists pos_inventory_movements_unacked_idx on public.pos_inventory_movements(restaurant_id,acknowledged_at,sequence);
create index if not exists pos_inventory_movements_order_idx on public.pos_inventory_movements(order_id);
alter table public.pos_inventory_movements enable row level security;
revoke all on public.pos_inventory_movements from anon;
revoke insert,update,delete on public.pos_inventory_movements from authenticated;
grant select on public.pos_inventory_movements to authenticated;
drop policy if exists pos_inventory_movements_select on public.pos_inventory_movements;
create policy pos_inventory_movements_select on public.pos_inventory_movements
for select to authenticated using (public.is_restaurant_member(restaurant_id));

CREATE OR REPLACE FUNCTION public.pos_ack_inventory_movements(p_restaurant_id uuid, p_movement_ids uuid[], p_actor_user_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_rest public.restaurants%rowtype;
  v_count integer:=0;
begin
  select * into v_rest from public.restaurants where id=p_restaurant_id and active=true;
  if not found then raise exception 'RESTAURANT_NOT_FOUND'; end if;
  if not public.pos_actor_is_manager(p_actor_user_id,v_rest.organization_id,p_restaurant_id) then
    raise exception 'MANAGER_ACCESS_REQUIRED';
  end if;
  if p_movement_ids is null or cardinality(p_movement_ids)=0 then return 0; end if;

  update public.pos_inventory_movements
  set acknowledged_at=coalesce(acknowledged_at,now()),
      acknowledged_by=coalesce(acknowledged_by,p_actor_user_id)
  where restaurant_id=p_restaurant_id and id=any(p_movement_ids);
  get diagnostics v_count=row_count;
  return v_count;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pos_food_cost_report(p_restaurant_id uuid, p_business_date date, p_actor_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_rest public.restaurants%rowtype;
  v_sales numeric(14,2):=0;
  v_cost numeric(14,2):=0;
  v_lines integer:=0;
  v_mapped_lines integer:=0;
begin
  select * into v_rest from public.restaurants where id=p_restaurant_id and active=true;
  if not found then raise exception 'RESTAURANT_NOT_FOUND'; end if;
  if not public.pos_actor_has_access(p_actor_user_id,v_rest.organization_id,p_restaurant_id) then
    raise exception 'POS_ACCESS_DENIED';
  end if;

  select
    coalesce(sum(i.line_total),0)::numeric(14,2),
    coalesce(sum(i.cost_total),0)::numeric(14,2),
    count(*)::integer
  into v_sales,v_cost,v_lines
  from public.pos_order_items i
  join public.pos_orders o on o.id=i.order_id
  where o.restaurant_id=p_restaurant_id
    and o.business_date=p_business_date
    and o.status in ('paid','refunded')
    and i.kitchen_status<>'cancelled';

  select count(distinct m.order_item_id)::integer into v_mapped_lines
  from public.pos_inventory_movements m
  where m.restaurant_id=p_restaurant_id and m.business_date=p_business_date and m.kind='sale';

  return jsonb_build_object(
    'restaurantId',p_restaurant_id,'businessDate',p_business_date,
    'sales',v_sales,'theoreticalFoodCost',v_cost,
    'foodCostPct',case when v_sales>0 then round(v_cost/v_sales*100,2) else 0 end,
    'grossMargin',round(v_sales-v_cost,2),
    'lineCount',v_lines,'mappedLineCount',v_mapped_lines
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.pos_order_item_cost_snapshot()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_cost numeric(14,4):=0;
begin
  if new.catalog_item_id is not null then
    select greatest(0,coalesce(nullif(metadata->>'unitCost','')::numeric,0))
    into v_cost
    from public.pos_catalog_items
    where id=new.catalog_item_id;
  end if;
  new.unit_cost_snapshot:=coalesce(v_cost,0);
  new.cost_total:=round(new.unit_cost_snapshot*new.quantity,2);
  return new;
exception when others then
  new.unit_cost_snapshot:=0;
  new.cost_total:=0;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pos_order_paid_inventory_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.status='paid' and (tg_op='INSERT' or old.status is distinct from 'paid') then
    perform public.pos_record_order_consumption(new.id);
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.pos_record_order_consumption(p_order_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_order public.pos_orders%rowtype;
  v_line record;
  v_component jsonb;
  v_source text;
  v_stock_id text;
  v_name text;
  v_unit text;
  v_per_unit numeric(14,4);
  v_unit_cost numeric(14,4);
  v_qty numeric(14,4);
  v_inserted integer:=0;
begin
  select * into v_order from public.pos_orders where id=p_order_id;
  if not found or v_order.status<>'paid' then return 0; end if;

  for v_line in
    select i.id,i.catalog_item_id,i.quantity,c.metadata
    from public.pos_order_items i
    left join public.pos_catalog_items c on c.id=i.catalog_item_id
    where i.order_id=p_order_id and i.kitchen_status<>'cancelled'
  loop
    if jsonb_typeof(v_line.metadata->'stockComponents')<>'array' then continue; end if;
    for v_component in select value from jsonb_array_elements(v_line.metadata->'stockComponents')
    loop
      v_stock_id:=nullif(left(trim(coalesce(v_component->>'stockId','')),180),'');
      v_source:=left(trim(coalesce(v_component->>'sourceKey',case when v_stock_id is not null then 'stock:'||v_stock_id else '' end)),240);
      v_name:=left(trim(coalesce(v_component->>'name','Stock')),240);
      v_unit:=left(trim(coalesce(v_component->>'unit','unit')),40);
      v_per_unit:=greatest(0,coalesce(nullif(v_component->>'quantity','')::numeric,0));
      v_unit_cost:=greatest(0,coalesce(nullif(v_component->>'unitCost','')::numeric,0));
      if v_source='' or v_per_unit<=0 then continue; end if;
      v_qty:=round(v_line.quantity*v_per_unit,4);

      insert into public.pos_inventory_movements(
        organization_id,restaurant_id,order_id,order_item_id,catalog_item_id,
        hub_stock_id,stock_source_key,stock_name,unit,kind,quantity_delta,
        unit_cost,total_cost,business_date,receipt_number
      ) values(
        v_order.organization_id,v_order.restaurant_id,v_order.id,v_line.id,v_line.catalog_item_id,
        v_stock_id,v_source,v_name,v_unit,'sale',-v_qty,
        v_unit_cost,round(v_qty*v_unit_cost,2),v_order.business_date,v_order.receipt_number
      )
      on conflict(order_item_id,stock_source_key,kind) do nothing;
      if found then v_inserted:=v_inserted+1; end if;
    end loop;
  end loop;
  return v_inserted;
end;
$function$;



drop trigger if exists pos_order_item_cost_snapshot_trigger on public.pos_order_items;
create trigger pos_order_item_cost_snapshot_trigger
before insert on public.pos_order_items
for each row execute function public.pos_order_item_cost_snapshot();

drop trigger if exists pos_order_paid_inventory_trigger on public.pos_orders;
create trigger pos_order_paid_inventory_trigger
after insert or update of status on public.pos_orders
for each row execute function public.pos_order_paid_inventory_trigger();

revoke all on function public.pos_order_item_cost_snapshot() from public,anon,authenticated;
revoke all on function public.pos_record_order_consumption(uuid) from public,anon,authenticated;
revoke all on function public.pos_order_paid_inventory_trigger() from public,anon,authenticated;
revoke all on function public.pos_ack_inventory_movements(uuid,uuid[],uuid) from public,anon,authenticated;
revoke all on function public.pos_food_cost_report(uuid,date,uuid) from public,anon,authenticated;
grant execute on function public.pos_order_item_cost_snapshot() to service_role;
grant execute on function public.pos_record_order_consumption(uuid) to service_role;
grant execute on function public.pos_order_paid_inventory_trigger() to service_role;
grant execute on function public.pos_ack_inventory_movements(uuid,uuid[],uuid) to service_role;
grant execute on function public.pos_food_cost_report(uuid,date,uuid) to service_role;
