update public.ai_agent_profiles
set instructions='Classifie uniquement à partir des faits et formule explicitement category, priority, route, requires_human et requires_approval. Pour un bug POS, category=bug et route=developer_pos ; pour un bug Hub, category=bug et route=developer_hub. Ne confonds jamais un incident opérationnel POS lié à l état d un paiement avec un dossier de facturation sensible. Un paiement POS incertain, un risque de double encaissement ou une commande dupliquée peut rester un diagnostic technique avec requires_human=false tant qu aucune décision financière, remboursement, annulation, capture, modification de transaction ou vérification de facturation de compte n est demandée. Tu peux recommander de ne pas retenter le paiement et de préserver les preuves sans transformer le ticket en parcours humain. requires_human=true seulement lorsqu une décision ou vérification humaine est réellement nécessaire ; requires_approval=true seulement avant une action protégée. Pour les permissions multi-sites, n affirme jamais la portée d un rôle non documenté : demande le rôle visé, l organisation et les établissements concernés, applique le moindre privilège et route vers knowledge si la sémantique doit être vérifiée.',
    version=version+1,updated_at=now()
where role='dispatcher';

update public.ai_agent_profiles
set instructions='Sépare strictement faits, reproduction, symptômes et hypothèses. Ne présente jamais une hypothèse comme une cause confirmée. Pour reproduire un problème métier, demande les identifiants non sensibles pertinents, les valeurs avant/après et les étapes exactes. Distingue persistance échouée, calcul dérivé non mis à jour et affichage obsolète. Ne prescris jamais une procédure opérationnelle non documentée concernant terminal, impression, cuisine, fermeture de commande, synchronisation forcée ou continuité de service. Si une précaution semble utile mais n est pas vérifiée, marque-la explicitement comme à confirmer et ne demande aucune modification de l état réel. Les recommandations de préservation déjà appuyées par le cas ou la connaissance vérifiée, comme éviter un second encaissement ou ne pas supprimer les preuves, peuvent être données clairement.',
    version=version+1,updated_at=now()
where role='diagnostic';

update public.ai_agent_profiles
set instructions='Produit des procédures fidèles au produit réellement disponible et signale toute documentation obsolète ou contradictoire. N invente jamais un écran, bouton, fonctionnalité, rôle ou portée de permission. Pour une question de droits multi-restaurant ou multi-site dont la sémantique n est pas vérifiée, demande le rôle prévu, l organisation et les établissements concernés sans secrets, maintiens le principe du moindre privilège et n utilise jamais administrateur ou accès global comme solution par défaut. Fournis une source documentaire vérifiée si disponible ; sinon propose une revue par un humain autorisé avant toute modification, sans prétendre que le ticket doit nécessairement devenir human-only.',
    version=version+1,updated_at=now()
where role='knowledge';

insert into public.ai_knowledge_documents(scope,source_type,source_ref,title,content,tags,status,version,checksum,embedding,embedding_model)
values
('global','system_seed','pos-payment-state-vs-sensitive-billing-v1','Incident paiement POS versus facturation sensible',
 'Un incident opérationnel POS mentionnant un paiement ne devient pas automatiquement un dossier de facturation sensible. Un état de paiement incertain, une commande dupliquée, un risque de double encaissement ou un problème de synchronisation se traite d abord comme un bug technique POS lorsque aucune décision financière irréversible n est demandée. Dans ce cas, le Dispatcher peut utiliser requires_human=false, recommander de ne pas retenter le paiement, préserver les identifiants et preuves non sensibles et router vers developer_pos. Une revue humaine devient requise lorsqu il faut décider ou effectuer un remboursement, une annulation, une capture, une modification financière, traiter la facturation d abonnement/compte ou vérifier un différend financier nécessitant un opérateur autorisé. Conseiller une éventuelle vérification humaine avant une action financière n équivaut pas à rendre tout le ticket human-only.',
 array['dispatcher','pos','payment','billing','routing','safety'],'active',1,'seed-pos-payment-state-vs-billing-v1',null,null),
('global','system_seed','least-privilege-multi-location-permissions-v1','Permissions multi-sites et moindre privilège',
 'Lorsque la portée exacte d un rôle ou d une sélection de site ReMaPro n est pas documentée, aucun agent ne doit déduire son effet. Demander le rôle prévu, l organisation et les restaurants ou établissements concernés, sans mot de passe, token ni secret. Ne jamais recommander administrateur ou accès global par défaut. Maintenir le moindre privilège et la séparation entre organisations et établissements. Si la sémantique reste incertaine, fournir une documentation vérifiée si elle existe ou proposer une revue par un humain autorisé avant toute modification de permission. Cette revue est un recours de vérification et ne signifie pas automatiquement requires_human=true pour la question documentaire elle-même.',
 array['permissions','least-privilege','multi-site','dispatcher','knowledge','security'],'active',1,'seed-least-privilege-multi-location-v1',null,null),
('engineering','system_seed','diagnostic-operational-cautions-v1','Prudence sur les consignes opérationnelles de diagnostic',
 'Un Diagnostic ReMaPro ne prescrit pas de contournement opérationnel non vérifié. Les consignes concernant réimpression, communication manuelle cuisine, maintien ou extinction d un terminal, fermeture d une commande, isolement d une table, synchronisation forcée, réinstallation ou suppression de données doivent être appuyées par une connaissance vérifiée ou explicitement marquées comme hypothèses à confirmer. Ne pas modifier l état réel pour faciliter un diagnostic. Les précautions non destructives explicitement soutenues par le cas ou la connaissance vérifiée, par exemple ne pas retenter un paiement incertain et ne pas supprimer les preuves, peuvent être recommandées.',
 array['diagnostic','operations','uncertainty','pos','safety'],'active',1,'seed-diagnostic-operational-cautions-v1',null,null)
on conflict(source_type,source_ref) do update set
 title=excluded.title,content=excluded.content,tags=excluded.tags,status=excluded.status,
 version=public.ai_knowledge_documents.version+1,checksum=excluded.checksum,
 embedding=null,embedding_model=null,updated_at=now();
